app/src/main/java/org/jboss/hal/client/configuration/SocketBindingGroupPresenter.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/ee/EEPresenter.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/ElytronColumn.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/ElytronPresenter.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/FactoriesPresenter.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/FactoriesView.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/OtherSettingsPresenter.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/OtherSettingsView.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/RealmsPresenter.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/RealmsView.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/ResourceView.java
core/src/main/java/org/jboss/hal/core/CrudOperations.java
core/src/main/java/org/jboss/hal/core/OperationFactory.java
core/src/main/java/org/jboss/hal/core/mbui/form/ComplexAttributeModelNodeForm.java
dmr/src/main/java/org/jboss/hal/dmr/ModelDescriptionConstants.java
meta/src/main/java/org/jboss/hal/meta/Metadata.java

* add complex attribute as pages
* add support to list-add,list-remove operations on LISTs
* ability to show custom columns on tables for sub-pages

Elytron subsystem - WIP

---

flow/src/main/java/org/jboss/hal/flow/Flow.java
flow/src/main/java/org/jboss/hal/flow/Step.java

Each step is a map from `T -> Single<T>`. But this is just a current limitation, usually, the map is from `T -> Single<V>`. I prefer the term Task instead of step, bc step has the implication of something in the middle. And, most of Step implementation are just task. The nice thing with RX is that all your task can be wrapped in an RX type, these types are optionally lazy and optionally async. And whatever decision you choose in how you emit lazy/eager async/sync will not affect how you consume the data (ehmm... eager and lazy might have side effects, hehe but yep, it is obvious).
So, IMO Step will eventually just disappear bc you just need to return any RX type from a method, the arguments of the method is T (input) and the RX generics is V (output).

Revealing the true nature of Step

---

app/src/main/java/org/jboss/hal/client/deployment/wizard/NamesStep.java

https://issues.jboss.org/browse/HAL-1402

HAL-1402 - Error in add deployment wizard in domain mode

---

app/src/less/header.less
app/src/main/java/org/jboss/hal/client/bootstrap/endpoint/EndpointManager.java
app/src/main/java/org/jboss/hal/client/bootstrap/tasks/CheckTargetVersion.java
app/src/main/java/org/jboss/hal/client/skeleton/HeaderPresenter.java
js/src/main/java/org/jboss/hal/js/JsHelper.java

https://issues.jboss.org/browse/HAL-1401

HAL-1401: Fix connect to a different server

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/OtherSettingsPresenter.java
resources/src/main/java/org/jboss/hal/resources/Messages.java
resources/src/main/resources/org/jboss/hal/resources/Messages.properties

https://issues.jboss.org/browse/HAL-1441

HAL-1441 Not possible to create Elytron credential store using new console

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/DataSourceTemplates.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/DataSourceView.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/wizard/DataSourceWizard.java
ballroom/src/main/java/org/jboss/hal/ballroom/wizard/Wizard.java
dmr/src/main/java/org/jboss/hal/dmr/ModelDescriptionConstants.java

https://issues.jboss.org/browse/HAL-1155
HAL-1440 Confusing behaviour of Add Datasource wizard
https://issues.jboss.org/browse/HAL-1440
Organized attribute list of DatasourceView

HAL-1155 XA Datasource wizard does not add <xa-datasource-class> element in configuration when using deployed JDBC driver

---

app/src/main/resources/org/jboss/hal/client/configuration/subsystem/messaging/ClusteringView.mbui.xml

https://issues.jboss.org/browse/HAL-1444

HAL-1444 Issues when editing messaging server broadcast and discovery group

---

app/src/main/java/org/jboss/hal/client/deployment/ContentColumn.java
app/src/main/java/org/jboss/hal/client/deployment/ContentPreview.java
resources/src/main/java/org/jboss/hal/resources/Messages.java
resources/src/main/resources/org/jboss/hal/resources/Messages.properties
resources/src/main/resources/org/jboss/hal/resources/Messages_pt_BR.properties

https://issues.jboss.org/browse/HAL-1445

HAL-1445 Only allow browse content for managed deployments

---

app/src/main/java/org/jboss/hal/client/deployment/ContentColumn.java
app/src/main/java/org/jboss/hal/client/deployment/ContentPreview.java
resources/src/main/java/org/jboss/hal/resources/Messages.java
resources/src/main/resources/org/jboss/hal/resources/Messages.properties
resources/src/main/resources/org/jboss/hal/resources/Messages_pt_BR.properties

https://issues.jboss.org/browse/HAL-1450
Also shows the "path" attribute for unmanaged deployments.

HAL-1450 Only show "download" option for managed and archive deployment

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/undertow/FilterPresenter.java
ballroom/src/main/java/org/jboss/hal/ballroom/form/AbstractFormItem.java
core/src/main/java/org/jboss/hal/core/expression/Expression.java
core/src/main/java/org/jboss/hal/core/expression/ExpressionResolver.java
core/src/test/java/org/jboss/hal/core/expression/ExpressionTest.java
dmr/src/main/java/org/jboss/hal/dmr/dispatch/Dispatcher.java
processors/src/main/java/org/jboss/hal/processor/mbui/ExpressionParser.java

HAL-1448 "Name" field is not present when creating new Undertow's Response Header
https://issues.jboss.org/browse/HAL-1448
HAL-1449 Cannot edit file handler attribute in Undertow's handler configuration
https://issues.jboss.org/browse/HAL-1449
HAL-1451 Incorrect test of expression values
https://issues.jboss.org/browse/HAL-1451

Fix add response-header and expression handling

---

core/src/main/java/org/jboss/hal/core/mbui/form/DefaultFormItemProvider.java

https://issues.jboss.org/browse/HAL-1447

HAL-1447: Enable form items for runtime attributes

---

core/src/main/java/org/jboss/hal/core/mbui/form/DefaultFormItemProvider.java

https://issues.jboss.org/browse/HAL-1447

Consider "metric" access-type for HAL-1447: Enable form items for runtime attributes

---

app/src/main/java/org/jboss/hal/client/deployment/dialog/AddUnmanagedDialog.java
core/src/main/java/org/jboss/hal/core/mbui/form/RequiredByValidation.java

https://issues.jboss.org/browse/HAL-1458

HAL-1458 Add unmanaged deployment doesn't work for directory apps

---

app/src/main/java/org/jboss/hal/client/deployment/StandaloneDeploymentView.java
ballroom/src/main/java/org/jboss/hal/ballroom/Tabs.java
core/src/main/java/org/jboss/hal/core/mbui/form/DefaultFormItemProvider.java

https://issues.jboss.org/browse/HAL-1460
* Also, disable expression for read only form item

HAL-1460 Disable Content navigation for unmanaged deployments in standalone mode

---

app/src/main/java/org/jboss/hal/client/ConsoleModule.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/undertow/AddressTemplates.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/undertow/ByteBufferPoolPresenter.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/undertow/ByteBufferPoolView.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/undertow/UndertowSettingsColumn.java
app/src/main/resources/org/jboss/hal/client/configuration/subsystem/undertow/ByteBufferPoolView.mbui.xml
dmr/src/main/java/org/jboss/hal/dmr/ModelDescriptionConstants.java
meta/src/main/java/org/jboss/hal/meta/token/NameTokens.java
resources/src/main/java/org/jboss/hal/resources/Names.java
resources/src/main/java/org/jboss/hal/resources/Previews.java
resources/src/main/resources/org/jboss/hal/resources/previews/configuration/undertow-byte-buffer-pool.html

https://issues.jboss.org/browse/HAL-1461

HAL-1461 Add byte-buffer-pool undertow resource to HAL

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/SubsystemColumn.java

https://issues.jboss.org/browse/HAL-1462

HAL-1462 Hide configuration screens that doesn't contain any attribute or sub-resources

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/logging/AddressTemplates.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/logging/LoggingPresenter.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/logging/LoggingProfilePresenter.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/logging/LoggingProfileView.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/logging/LoggingView.java
app/src/main/java/org/jboss/hal/client/skeleton/AboutDialog.java
app/src/main/resources/org/jboss/hal/client/configuration/subsystem/logging/LoggingProfileView.mbui.xml
app/src/main/resources/org/jboss/hal/client/configuration/subsystem/logging/LoggingView.mbui.xml
ballroom/src/main/java/org/jboss/hal/ballroom/LabelBuilder.java
core/src/main/java/org/jboss/hal/core/CrudOperations.java
dmr/src/main/java/org/jboss/hal/dmr/ModelDescriptionConstants.java
resources/src/main/java/org/jboss/hal/resources/Ids.java
resources/src/main/java/org/jboss/hal/resources/Names.java

HAL-1463 Add support to xml and json logging formatters
https://issues.jboss.org/browse/HAL-1463
HAL-1456 Duplicate line in about dialog
https://issues.jboss.org/browse/HAL-1456

HAL-1463 Add support to xml and json logging formatters, HAL-1456 Duplicate line in about dialog

---

app/refresh.sh
app/src/main/java/org/jboss/hal/client/ConsoleModule.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/securitymanager/AddressTemplates.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/securitymanager/Permission.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/securitymanager/SecurityManagerPresenter.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/securitymanager/SecurityManagerView.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/webservice/WebserviceView.java
core/src/main/java/org/jboss/hal/core/ComplexAttributeOperations.java
core/src/main/java/org/jboss/hal/core/mbui/dialog/AddResourceDialog.java
core/src/main/java/org/jboss/hal/core/subsystem/Subsystems.java
dmr/src/main/java/org/jboss/hal/dmr/ModelDescriptionConstants.java
meta/src/main/java/org/jboss/hal/meta/token/NameTokens.java
resources/src/main/java/org/jboss/hal/resources/Ids.java
resources/src/main/java/org/jboss/hal/resources/Messages.java
resources/src/main/java/org/jboss/hal/resources/Names.java
resources/src/main/resources/org/jboss/hal/resources/Messages.properties

https://issues.jboss.org/browse/HAL-1225

HAL-1225: Add dedicated UI for security-manager subsystem

---

app/src/main/java/org/jboss/hal/client/runtime/subsystem/elytron/ElytronRealmWithIdentity.java
app/src/main/java/org/jboss/hal/client/runtime/subsystem/elytron/wizardpassword/ConfigurePasswordStep.java
app/src/main/java/org/jboss/hal/client/runtime/subsystem/elytron/wizardpassword/PasswordWizard.java
app/src/main/java/org/jboss/hal/client/runtime/subsystem/elytron/wizardpassword/ReviewPasswordStep.java
dmr/src/main/java/org/jboss/hal/dmr/BytesModelValue.java

Enhance the set password wizard to show a header and description

Fix DMR write byte array

---

app/src/main/resources/org/jboss/hal/client/configuration/subsystem/logging/LoggingProfileView.mbui.xml
core/src/main/java/org/jboss/hal/core/mbui/form/ModelNodeForm.java
dmr/src/main/java/org/jboss/hal/dmr/ModelDescriptionConstants.java

https://issues.jboss.org/browse/HAL-1469
* Check for formItem == null validation on ModelNodeForm
* Fix typo in ModelDescriptionConstants

HAL-1469 Unable to read or edit categories in logging profile

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/DataSourcePresenter.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/DataSourceView.java
dmr/src/main/java/org/jboss/hal/dmr/ModelDescriptionConstants.java

https://issues.jboss.org/browse/HAL-756

HAL-756 Add datasource connection properties

---

ballroom/src/main/java/org/jboss/hal/ballroom/form/PropertiesItem.java
ballroom/src/main/java/org/jboss/hal/ballroom/form/TagsItem.java
ballroom/src/main/java/org/jboss/hal/ballroom/form/TagsManager.java
resources/src/main/java/org/jboss/hal/resources/Constants.java
resources/src/main/java/org/jboss/hal/resources/Messages.java
resources/src/main/resources/org/jboss/hal/resources/Constants.properties
resources/src/main/resources/org/jboss/hal/resources/Constants_pt_BR.properties
resources/src/main/resources/org/jboss/hal/resources/Messages.properties

https://issues.jboss.org/browse/HAL-1472

HAL-1472 Cannot enter specific characters in XA properties values

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/DataSourcePresenter.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/DataSourceView.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/JdbcDriverColumn.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/JdbcDriverPreview.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/wizard/DataSourceWizard.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/wizard/PropertiesStep.java
ballroom/src/main/java/org/jboss/hal/ballroom/autocomplete/StaticAutoComplete.java
ballroom/src/main/java/org/jboss/hal/ballroom/form/PropertiesItem.java
core/src/main/java/org/jboss/hal/core/datasource/JdbcDriver.java
dmr/src/main/java/org/jboss/hal/dmr/ModelDescriptionConstants.java
resources/src/main/java/org/jboss/hal/resources/Messages.java
resources/src/main/resources/org/jboss/hal/resources/Messages.properties

https://issues.jboss.org/browse/HAL-1481

HAL-1481 Provide datasource properties as suggestions

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/remoting/RemotingView.java
app/src/main/resources/org/jboss/hal/client/configuration/subsystem/remoting/RemotingView.mbui.xml

https://issues.jboss.org/browse/HAL-1411

HAL-1411 Change "Endpoint Configuration" view for remoting subsystem

---

app/src/main/java/org/jboss/hal/client/deployment/StandaloneDeploymentColumn.java
resources/src/main/java/org/jboss/hal/resources/Constants.java
resources/src/main/resources/org/jboss/hal/resources/Constants.properties
resources/src/main/resources/org/jboss/hal/resources/Constants_pt_BR.properties

https://issues.jboss.org/browse/HAL-1486

HAL-1486 Missing replace operation for deployment

---

app/src/main/java/org/jboss/hal/client/deployment/dialog/CreateEmptyDialog.java

https://issues.jboss.org/browse/HAL-1491

HAL-1491 Create Empty Deployment dialog is missing close or cancel buttons

---

ballroom/src/main/java/org/jboss/hal/ballroom/form/NumberDoubleItem.java
core/src/main/java/org/jboss/hal/core/mbui/form/DefaultFormItemProvider.java
core/src/main/java/org/jboss/hal/core/mbui/form/ModelNodeMapping.java
resources/src/main/java/org/jboss/hal/resources/Messages.java

https://issues.jboss.org/browse/HAL-1496

HAL-1496 Add support for ModelType.DOUBLE

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/logging/AddressTemplates.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/logging/LoggingPresenter.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/logging/LoggingProfilePresenter.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/logging/LoggingProfileView.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/logging/LoggingView.java
app/src/main/resources/org/jboss/hal/client/configuration/subsystem/logging/LoggingProfileView.mbui.xml
app/src/main/resources/org/jboss/hal/client/configuration/subsystem/logging/LoggingView.mbui.xml
core/src/main/java/org/jboss/hal/core/OperationFactory.java
core/src/main/java/org/jboss/hal/core/mbui/MbuiViewImpl.java
dmr/src/main/java/org/jboss/hal/dmr/ModelDescriptionConstants.java
processors/src/main/resources/org/jboss/hal/processor/mbui/templates/MbuiView.ftl
resources/src/main/java/org/jboss/hal/resources/Names.java

https://issues.jboss.org/browse/HAL-1501
HAL-1506 Skip undefine-attribute for attributes that doesn't exist as a result of alternatives checking
https://issues.jboss.org/browse/HAL-1506

HAL-1501 Support socket log handler

---

config/src/main/java/org/jboss/hal/config/AbstractEnvironment.java
config/src/main/java/org/jboss/hal/config/OperationMode.java

https://issues.jboss.org/browse/HAL-1512

HAL-1512 Support Wildfly in EMBEDDED mode

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/messaging/ServerColumn.java
app/src/main/module-i18n.gwt.xml
versionBump.sh

HAL-1514 Add messaging server requires the path=* subresources if a server already exists
https://issues.jboss.org/browse/HAL-1514
* Also a small fix to versionBump.sh to update module-i18n.gwt.xml

HAL-1514 Add messaging server requires the path=* subresources if a server already exists

---

app/src/main/java/org/jboss/hal/client/deployment/DeploymentTasks.java
app/src/main/java/org/jboss/hal/client/deployment/dialog/DeployContentDialog1.java
app/src/main/java/org/jboss/hal/client/deployment/dialog/DeployContentDialog2.java
app/src/main/java/org/jboss/hal/client/deployment/wizard/NamesStep.java

https://issues.jboss.org/browse/HAL-1513

HAL-1513 Enable deployments by default

---

core/src/main/java/org/jboss/hal/core/mbui/form/DefaultFormItemProvider.java

https://issues.jboss.org/browse/HAL-1520

HAL-1520 ModelBrowser form doesn't show values if they are expressions and read-only

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/jca/AddressTemplates.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/jca/JcaPresenter.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/jca/JcaView.java

https://issues.jboss.org/browse/HAL-1515

HAL-1515 The "name" field of "Add" dialog for JCA distributed work manager is read only

---

app/src/main/java/org/jboss/hal/client/patching/wizard/RollbackStep.java
app/src/main/java/org/jboss/hal/client/patching/wizard/RollbackWizard.java

https://issues.jboss.org/browse/HAL-1526
* Also, remove the "view patch" action on the rollback wizard as there is no sense to show it after the rollback.

HAL-1526 Required field error when rolling back a patch

---

app/src/main/java/org/jboss/hal/client/deployment/ServerGroupDeploymentColumn.java
app/src/main/java/org/jboss/hal/client/deployment/StandaloneDeploymentColumn.java
ballroom/src/main/java/org/jboss/hal/ballroom/LabelBuilder.java

https://issues.jboss.org/browse/HAL-1519
(cherry picked from commit bfba37738deb6aaf9cabe5147ad115c9443dc36a)

HAL-1519 Undeploy operation wording is not unified

---

app/src/main/java/org/jboss/hal/client/runtime/subsystem/logging/AddressTemplates.java
app/src/main/java/org/jboss/hal/client/runtime/subsystem/logging/LogFile.java
app/src/main/java/org/jboss/hal/client/runtime/subsystem/logging/LogFileColumn.java
app/src/main/java/org/jboss/hal/client/runtime/subsystem/logging/LogFilePresenter.java
app/src/main/java/org/jboss/hal/client/runtime/subsystem/logging/LogFilePreview.java
app/src/main/java/org/jboss/hal/client/runtime/subsystem/logging/LogFileView.java
app/src/main/java/org/jboss/hal/client/runtime/subsystem/logging/LogFiles.java
dmr/src/main/java/org/jboss/hal/dmr/ModelDescriptionConstants.java
resources/src/main/java/org/jboss/hal/resources/Constants.java
resources/src/main/resources/org/jboss/hal/resources/Constants.properties
resources/src/main/resources/org/jboss/hal/resources/Constants_pt_BR.properties

https://issues.jboss.org/browse/HAL-1507

HAL-1507 Show logs from logging-profile in log viewer

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/AddressTemplates.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/ElytronResource.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/OtherSettingsPresenter.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/OtherSettingsView.java
dmr/src/main/java/org/jboss/hal/dmr/ModelDescriptionConstants.java
resources/src/main/java/org/jboss/hal/resources/Ids.java

https://issues.jboss.org/browse/HAL-1521

HAL-1521 Add support for JASPI as added to the WildFly Elytron Subsystem

---

app/src/main/java/org/jboss/hal/client/runtime/subsystem/elytron/KeyStoreElement.java
app/src/main/java/org/jboss/hal/client/runtime/subsystem/elytron/StoresPresenter.java

https://issues.jboss.org/browse/HAL-1546

HAL-1546 Obtain certificate button of key-store runtime view should use a new alias

---

app/src/main/java/org/jboss/hal/client/ConsoleModule.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/microprofile/AddressTemplates.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/microprofile/MicroProfileConfigPresenter.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/microprofile/MicroProfileMetricsPresenter.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/microprofile/MicroProfileMetricsView.java
app/src/main/java/org/jboss/hal/client/runtime/subsystem/microprofile/health/MicroProfileHealthView.java
ballroom/src/main/java/org/jboss/hal/ballroom/autocomplete/ReadChildrenAutoComplete.java
core/src/main/java/org/jboss/hal/core/subsystem/Subsystems.java
dmr/src/main/java/org/jboss/hal/dmr/ModelDescriptionConstants.java
meta/src/main/java/org/jboss/hal/meta/token/NameTokens.java
resources/src/main/java/org/jboss/hal/resources/Ids.java
resources/src/main/java/org/jboss/hal/resources/Names.java
resources/src/main/java/org/jboss/hal/resources/Previews.java
resources/src/main/resources/org/jboss/hal/resources/previews/configuration/microprofile-metrics.html

https://issues.jboss.org/browse/HAL-1537

HAL-1537: Support Eclipse MicroProfile Metrics in Web Console

---

app/src/main/java/org/jboss/hal/client/runtime/subsystem/logging/LogFileView.java

https://issues.jboss.org/browse/HAL-1550

HAL-1550 Broken Tail Mode button when log viewer displayed repeatedly

---

app/src/main/java/org/jboss/hal/client/runtime/subsystem/microprofile/health/MicroProfileHealthPresenter.java
core/src/main/java/org/jboss/hal/core/subsystem/Subsystems.java

https://issues.jboss.org/browse/HAL-1551

HAL-1551 Set the smallrye subtitle for microprofile-health columns

---

app/src/main/java/org/jboss/hal/client/tools/MacroEditorView.java
app/src/main/java/org/jboss/hal/client/tools/MacroOptionsDialog.java
core/src/main/java/org/jboss/hal/core/mbui/dialog/ModifyResourceDialog.java
dmr/src/main/java/org/jboss/hal/dmr/macro/Macro.java
dmr/src/main/java/org/jboss/hal/dmr/macro/Macros.java

https://issues.jboss.org/browse/HAL-1552

HAL-1552: Fix macro recording; remove unimplemented features

---

app/src/main/java/org/jboss/hal/client/runtime/server/ServerPreview.java

Fix server.readUrl only in running state.

Fix show "open ports" header in server preview only in running state.

---

app/src/main/java/org/jboss/hal/client/runtime/server/ServerPreview.java
ballroom/src/main/java/org/jboss/hal/ballroom/form/EditingAppearance.java
core/src/main/java/org/jboss/hal/core/mbui/form/DefaultFormItemProvider.java

Also a small fix to DefaultFormItemProvider to allow form.save when there is a read-only attribute.

Fix show "open ports" header in server preview for reload and restart mode

---

app/src/main/java/org/jboss/hal/client/bootstrap/HalPreBootstrapper.java
app/src/main/resources/org/jboss/hal/client/bootstrap/BootstrapFailed.html

https://issues.jboss.org/browse/HAL-1398

HAL-1398 Empty error message when connecting w/o user

---

core/src/main/java/org/jboss/hal/core/mbui/ResourceElement.java

https://issues.jboss.org/browse/HAL-1569

HAL-1569 Missing reset link on forms of elytron resources

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/DataSourceTemplates.java

https://issues.jboss.org/browse/HAL-1570

HAL-1570 Do not automatically set datasource-class at datasource wizard

---

pom.xml

https://issues.jboss.org/browse/HAL-1577

HAL-1577: Change use of HTTP download locations to HTTPS

---

app/src/main/java/org/jboss/hal/client/runtime/subsystem/io/WorkerPreview.java
ballroom/src/main/java/org/jboss/hal/ballroom/form/SwitchItem.java
dmr/src/main/java/org/jboss/hal/dmr/ModelDescriptionConstants.java

https://issues.jboss.org/browse/HAL-1576

[HAL-1576] Add BusyWorkerThreadCount metric in IO WorkerPreview

---

app/Gruntfile.js
app/package.json
app/src/less/hal.less
ballroom/src/main/java/org/jboss/hal/ballroom/PatternFly.java
ballroom/src/main/java/org/jboss/hal/ballroom/form/SwitchItem.java
parent-with-dependencies/pom.xml

https://issues.jboss.org/browse/HAL-1579

HAL-1579: Fix duplicate switch item initialization

---

core/src/main/java/org/jboss/hal/core/runtime/server/ServerUrlTasks.java
dmr/src/main/java/org/jboss/hal/dmr/ModelDescriptionConstants.java

https://issues.jboss.org/browse/HAL-1588

HAL-1588 added filtering for server urls only to bound ones

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/CustomListItem.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/MultiValueListItem.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/RoleMapListItem.java
app/src/main/java/org/jboss/hal/client/runtime/subsystem/elytron/IdentityAttributeItem.java
ballroom/src/main/java/org/jboss/hal/ballroom/form/ListItem.java
ballroom/src/main/java/org/jboss/hal/ballroom/form/PropertiesItem.java
ballroom/src/main/java/org/jboss/hal/ballroom/form/TagsItem.java
ballroom/src/main/java/org/jboss/hal/ballroom/form/TagsManager.java
ballroom/src/main/java/org/jboss/hal/ballroom/form/TagsMapping.java
ballroom/src/test/java/org/jboss/hal/ballroom/form/MapMappingTest.java

Issue: [HAL-1613](https://issues.jboss.org/browse/HAL-1613)
(Related to [JBEAP-16757](https://issues.jboss.org/browse/JBEAP-16757))

HAL-1613: improve tag handling

---

app/src/main/java/org/jboss/hal/client/runtime/configurationchanges/ConfigurationChange.java
app/src/main/java/org/jboss/hal/client/runtime/configurationchanges/ConfigurationChangeDisplay.java
app/src/main/java/org/jboss/hal/client/runtime/configurationchanges/ConfigurationChangesPresenter.java
resources/src/main/java/org/jboss/hal/resources/Constants.java
resources/src/main/resources/org/jboss/hal/resources/Constants.properties

https://issues.jboss.org/browse/HAL-1414

HAL-1414 Show as CLI command for configuration changes

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/CustomListItem.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/MultiValueListItem.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/RoleMapListItem.java
app/src/main/java/org/jboss/hal/client/runtime/subsystem/elytron/IdentityAttributeItem.java
ballroom/src/main/java/org/jboss/hal/ballroom/form/ListItem.java
ballroom/src/main/java/org/jboss/hal/ballroom/form/PropertiesItem.java
ballroom/src/main/java/org/jboss/hal/ballroom/form/TagsItem.java
ballroom/src/main/java/org/jboss/hal/ballroom/form/TagsManager.java
ballroom/src/main/java/org/jboss/hal/ballroom/form/TagsMapping.java

Backport of [HAL-1613](https://issues.jboss.org/browse/HAL-1613)
Issue: [JBEAP-16757](https://issues.jboss.org/browse/JBEAP-16757)

JBEAP-16757, HAL-1613: improve tag handling

---

ballroom/src/main/java/org/jboss/hal/ballroom/form/PropertiesItem.java
ballroom/src/test/java/org/jboss/hal/ballroom/form/MapMappingTest.java
meta/src/main/java/org/jboss/hal/meta/security/Constraints.java
meta/src/test/java/org/jboss/hal/meta/security/ConstraintTest.java
meta/src/test/java/org/jboss/hal/meta/security/ConstraintsTest.java

(cherry picked from commit 12963050348121061d6f9fb14046c5ce25030b16)
https://issues.jboss.org/browse/JBEAP-16310
https://issues.jboss.org/browse/HAL-1565
develop PR: https://github.com/hal/console/pull/298
This PR:
* cherry-pick 12963050348121061d6f9fb14046c5ce25030b16
* adds `data()` and `toString()` methods in `Constraints.java`
* updates the `HashSet` use to `LinkedHashSet` to respect ordering of constraints in `Constraints.java`
* updates validation of input argument in `PropertiesItem::parseTag(String)`

HAL-1565: Add [] as allowed characters in properties form item

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/logging/LoggingProfileView.java
app/src/main/resources/org/jboss/hal/client/configuration/subsystem/logging/LoggingProfileView.mbui.xml
app/src/main/resources/org/jboss/hal/client/configuration/subsystem/logging/LoggingView.mbui.xml

https://issues.jboss.org/browse/HAL-1601

HAL-1601: Expose named-formatter attribute for syslog-handler

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/RealmsPresenter.java

https://issues.jboss.org/browse/HAL-1609

HAL-1609: Configure new / enhanced password mappers

---

app/src/main/java/org/jboss/hal/client/runtime/subsystem/logging/AddressTemplates.java
app/src/main/java/org/jboss/hal/client/runtime/subsystem/logging/LogFile.java
app/src/main/java/org/jboss/hal/client/runtime/subsystem/logging/LogFileColumn.java
app/src/main/java/org/jboss/hal/client/runtime/subsystem/logging/LogFilePresenter.java
app/src/main/java/org/jboss/hal/client/runtime/subsystem/logging/LogFilePreview.java
app/src/main/java/org/jboss/hal/client/runtime/subsystem/logging/LogFileView.java
app/src/main/java/org/jboss/hal/client/runtime/subsystem/logging/LogFiles.java

https://issues.jboss.org/browse/HAL-1628
A backport from upstream to 3.0.x, see
https://issues.jboss.org/browse/HAL-1485
https://issues.jboss.org/browse/HAL-1507

[HAL-1628] Not able to view log files in admin console if its created via logging-profile

---

app/src/main/java/org/jboss/hal/client/deployment/ServerGroupDeploymentColumn.java

JIRA: https://issues.jboss.org/browse/HAL-1632

[HAL-1632] Deployment button not available for server group scoped role

---

app/Gruntfile.js
app/src/js/worker.js

https://issues.redhat.com/browse/HAL-1649

Hal 1649 3.0.x

---

app/src/js/worker.js

https://issues.redhat.com/browse/HAL-1649
follow up to https://github.com/hal/console/commit/76cfebcbcbc89af41fbd7e2cb0ed7c896dc6af76

JBEAP-17852 / HAL-1649 part2

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/infinispan/MemoryElement.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/infinispan/StoreElement.java

(cherry picked from commit 57d1f727b1d2a3e6dcb598a4d9f642bb6c3db899)
Issue: https://issues.jboss.org/browse/JBEAP-18102
This is fixed in version 3.2.1.Final in https://issues.jboss.org/browse/HAL-1627 
Please hold on the merging until PM ack is granted for CP. Thanks.

HAL-1627: Fix store and memory element

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/ElytronColumn.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/messaging/MessagingCategoryColumn.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/undertow/UndertowSettingsColumn.java
app/src/main/java/org/jboss/hal/client/runtime/subsystem/elytron/ElytronColumn.java

Component issue: https://issues.jboss.org/browse/HAL-1646

HAL-1646 Navigation doesn't remember chosen profile in some subsystems

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/distributableweb/Affinity.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/distributableweb/AffinityElement.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/distributableweb/DistributableWebPresenter.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/distributableweb/DistributableWebView.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/distributableweb/SessionManagement.java
app/src/main/resources/org/jboss/hal/client/configuration/subsystem/distributableweb/DistributableWebView.mbui.xml
ballroom/src/main/java/org/jboss/hal/ballroom/form/SelectBoxBridge.java
dmr/src/main/java/org/jboss/hal/dmr/ModelDescriptionConstants.java
resources/src/main/java/org/jboss/hal/resources/Constants.java
resources/src/main/java/org/jboss/hal/resources/Ids.java
resources/src/main/java/org/jboss/hal/resources/Names.java
resources/src/main/resources/org/jboss/hal/resources/Constants.properties

Issue: [HAL-1635](https://issues.jboss.org/browse/HAL-1635)
Replaced the auto-generated sections for session management with custom ones, added a tab with switcher for affinity. (Out of the four, only "ranked" affinity has attributes)
Added a public "enable" method to SelectBoxBridge because I needed it to be disabled when no row is selected.

HAL-1635: add affinity form to session managements

---

app/src/main/java/org/jboss/hal/client/runtime/host/HostColumn.java
core/src/main/java/org/jboss/hal/core/runtime/TopologyTasks.java
core/src/main/java/org/jboss/hal/core/runtime/host/HostActions.java
dmr/src/main/java/org/jboss/hal/dmr/dispatch/TimeoutHandler.java
resources/src/main/java/org/jboss/hal/resources/UIConstants.java

https://issues.redhat.com/browse/HAL-1653

HAL-1653: Fix wrong composite failure construction in timeout handler

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/DataSourceTemplates.java

XA-datasource class for mysql is pointing to wrong path

Fix for HAL-1659

---

app/package-lock.json
app/src/main/java/org/jboss/hal/client/runtime/BrowseByColumn.java
app/src/main/java/org/jboss/hal/client/runtime/server/ServerColumn.java

https://issues.redhat.com/browse/HAL-1663

HAL-1663: Two error dialog messages when DC is starting and user executes lifecycle operations on slave servers

---

core/src/main/java/org/jboss/hal/core/runtime/host/HostActions.java

https://issues.redhat.com/browse/HAL-1668

HAL-1668: Close blocking dialog after errors

---

app/src/main/java/org/jboss/hal/client/runtime/BrowseByColumn.java
app/src/main/java/org/jboss/hal/client/runtime/server/ServerColumn.java
core/src/main/java/org/jboss/hal/core/runtime/TopologyTasks.java

FinderContext.getPath() might be reversed after coming back from an application
https://issues.redhat.com/browse/HAL-1660

HAL-1660: Fix browseByHosts() / browseByServerGroups()

---

app/src/main/java/org/jboss/hal/client/runtime/server/ServerColumn.java
core/src/main/java/org/jboss/hal/core/runtime/Action.java
core/src/main/java/org/jboss/hal/core/runtime/server/ServerActions.java

https://issues.redhat.com/browse/HAL-1662

HAL-1662: Adjust finder path when servers have been stopped

---

ballroom/src/main/java/org/jboss/hal/ballroom/form/PropertiesItem.java

https://issues.redhat.com/browse/HAL-1670

[HAL-1670] added parentheses to allowed chars for properties

---

ballroom/src/main/java/org/jboss/hal/ballroom/form/PropertiesItem.java

https://issues.redhat.com/browse/HAL-1638

HAL-1638: Add '*' as allowed character for properties item

---

core/src/main/java/org/jboss/hal/core/mbui/form/ModelNodeForm.java
core/src/main/java/org/jboss/hal/core/modelbrowser/ModelBrowser.java
core/src/main/java/org/jboss/hal/core/modelbrowser/ResourcePanel.java

Issue: [JBEAP-18368](https://issues.redhat.com/browse/JBEAP-18368)
Upstream issue: [HAL-1669](https://issues.redhat.com/browse/HAL-1669)
Upstream PR: #372

HAL-1669: add object attribute support to model browser

---

ballroom/src/main/java/org/jboss/hal/ballroom/form/PropertiesItem.java

https://issues.redhat.com/browse/HAL-1671

Fix for HAL-1671

---

app/src/main/java/org/jboss/hal/client/runtime/subsystem/ejb/EjbColumn.java

Issue: [HAL-1658](https://issues.redhat.com/browse/HAL-1658)
follow-up to #365, the address wasn't constructed correctly

HAL-1658: fix address resolution

---

app/src/main/java/org/jboss/hal/client/runtime/subsystem/ejb/EjbColumn.java
dmr/src/main/java/org/jboss/hal/dmr/Composite.java

Issue: https://issues.redhat.com/browse/JBEAP-18911
Upstream issue: https://issues.redhat.com/browse/JBEAP-18910
Upstream PR: https://github.com/hal/console/pull/385

HAL-1658: fix address handling in composite operation

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/DataSourceTemplates.java

https://issues.redhat.com/browse/HAL-1678

Fix for HAL-1678

---

app/src/main/java/org/jboss/hal/client/bootstrap/tasks/ReadAuthentication.java

https://issues.redhat.com/browse/HAL-1677 fix for possible undefined host element for host-scoped-role
This is downstream PR for 3.0.x. JBEAP issue https://issues.redhat.com/browse/JBEAP-17564
upstream PR: https://github.com/hal/console/pull/389

HAL-1677 fix for possible undefined host element for host-scoped-role

---

app/src/main/java/org/jboss/hal/client/runtime/subsystem/messaging/JmsQueuePresenter.java

issue: https://issues.redhat.com/browse/HAL-1682
JBEAP issue: https://issues.redhat.com/browse/JBEAP-19262
The op name for move-message and move-messages are wrong.

HAL-1682 fix wrong op name for message moving

---

core/src/main/java/org/jboss/hal/core/OperationFactory.java

HAL issue: https://issues.redhat.com/browse/HAL-1684
JBEAP issue: https://issues.redhat.com/browse/JBEAP-19324
HAL-1684 It should not set value as expression if it's type List. Please see more information in https://issues.redhat.com/browse/JBEAP-19124

HAL-1684 It should not set value as expression if it's type List.

---

core/src/main/java/org/jboss/hal/core/modelbrowser/ReadChildren.java

Issue: [HAL-1683](https://issues.redhat.com/browse/HAL-1683)

HAL-1683: improve id generation in Model Browser

---

app/src/main/java/org/jboss/hal/client/deployment/ContentColumn.java
app/src/main/java/org/jboss/hal/client/deployment/ReplaceDeploymentPanel.java
app/src/main/java/org/jboss/hal/client/deployment/StandaloneDeploymentColumn.java

https://issues.redhat.com/browse/HAL-1629

[HAL-1629] Displaying loading panel during the replace of deployment

---

app/src/main/java/org/jboss/hal/client/homepage/TourSetup.java

issue: https://issues.redhat.com/browse/JBEAP-19199
HAL issue: https://issues.redhat.com/browse/HAL-1680

HAL-1680 correct urls for Access Control Users/Roles in TourSetup.

---

app/src/main/java/org/jboss/hal/client/runtime/host/AddressTemplates.java
app/src/main/java/org/jboss/hal/client/runtime/host/HostColumn.java
app/src/main/java/org/jboss/hal/client/runtime/host/HostPresenter.java

Issue: https://issues.redhat.com/browse/JBEAP-19793
Upstream (7.3.z): https://issues.redhat.com/browse/JBEAP-19752
Master issue: https://issues.redhat.com/browse/HAL-1657
Master PR: https://github.com/hal/console/pull/375

HAL-1657: Change metadata address templates for host related classes (partly undoes HAL-1640)

---

app/src/main/java/org/jboss/hal/client/runtime/subsystem/ejb/EjbView.java

Issue: [HAL-1685](https://issues.redhat.com/browse/HAL-1685)

hal-1685: show timers and method in EJBView

---

app/src/main/java/org/jboss/hal/client/bootstrap/BootstrapFailed.java
app/src/main/java/org/jboss/hal/client/bootstrap/endpoint/EndpointManager.java
app/src/main/java/org/jboss/hal/client/bootstrap/endpoint/RbacProviderFailed.java

https://issues.redhat.com/browse/HAL-636

[HAL-636] Enhancing the bootstrap server setup process

---

app/src/main/java/org/jboss/hal/client/bootstrap/tasks/ReadAuthentication.java
app/src/main/java/org/jboss/hal/client/deployment/ServerGroupDeploymentPreview.java
app/src/main/java/org/jboss/hal/client/runtime/server/ServerColumn.java
dmr/src/main/java/org/jboss/hal/dmr/ModelDescriptionConstants.java
dmr/src/main/java/org/jboss/hal/dmr/dispatch/Dispatcher.java

https://issues.redhat.com/browse/HAL-1687

HAL-1687: Fix read authentication step

---

ballroom/src/main/java/org/jboss/hal/ballroom/autocomplete/AutoComplete.java

Issue: [HAL-1698](https://issues.redhat.com/browse/HAL-1698)
EAP issue: [JBEAP-19883](https://issues.redhat.com/browse/JBEAP-19883)

HAL-1698: fix event instantiation in IE

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/DataSourceView.java
resources/src/main/java/org/jboss/hal/resources/Ids.java

Issue: https://issues.redhat.com/browse/JBEAP-19753

JBEAP-19753 [GSS](7.3.z) Tab display does not switch in the Data Source Configuration screen in zh_Hans or ja locale

---

core/src/main/java/org/jboss/hal/core/modelbrowser/ResourcePanel.java

Issue: [HAL-1705](https://issues.redhat.com/browse/HAL-1705)

HAL-1705: make object support ignore properties

---

.github/workflows/ci.yml

Signed-off-by: Ken Wills <kwills@redhat.com>

Initial version of github actions CI

---

app/src/main/java/org/jboss/hal/client/runtime/host/HostColumn.java
app/src/main/java/org/jboss/hal/client/runtime/server/ServerColumn.java
app/src/main/java/org/jboss/hal/client/runtime/server/StandaloneServerColumn.java

Issue: [HAL-1707](https://issues.redhat.com/browse/HAL-1707)

HAL-1707: pre-load service metadata, hide non-available service

---

app/package-lock.json
app/src/main/java/org/jboss/hal/client/runtime/subsystem/batch/BatchPreview.java
ballroom/src/main/java/org/jboss/hal/ballroom/autocomplete/ReadChildrenAutoComplete.java
dmr/src/main/java/org/jboss/hal/dmr/Operation.java
dmr/src/test/java/org/jboss/hal/dmr/OperationTest.java

the HAL does not resolve expressions in operation calls
https://issues.redhat.com/browse/HAL-1681

Fix for HAL-1681

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/DataSourceTemplates.java

Issue: https://issues.redhat.com/browse/HAL-1723
JBEAP issue: https://issues.redhat.com/browse/JBEAP-20592
This was actually fixed in HAL 2.8.26 with https://issues.redhat.com/browse/HAL-1098 and https://issues.redhat.com/browse/JBEAP-4509, in repository https://github.com/hal/core
Old PR https://github.com/hal/core/pull/210, but it seems the fix was not included when migrating HAL code to https://github.com/hal/console in HAL 3 development.
Upstream PR https://github.com/hal/console/pull/433

HAL-1723 update url in template for MS SQLServer datasource

---

app/src/main/java/org/jboss/hal/client/bootstrap/tasks/ReadEnvironment.java
app/src/main/java/org/jboss/hal/client/patching/HostPatchesColumn.java

JIRA: https://issues.redhat.com/browse/HAL-1714

[HAL-1714] Fix patching screen for domain servers on RPM installation

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/DataSourceTemplates.java
dmr/src/main/java/org/jboss/hal/dmr/ModelDescriptionConstants.java

issue: https://issues.redhat.com/browse/HAL-1715 
JBEAP issue: https://issues.redhat.com/browse/JBEAP-20494

HAL-1715 update Oracle default validation settings

---

app/package-lock.json
app/src/main/java/org/jboss/hal/client/runtime/subsystem/ejb/EjbColumn.java

JIRA: https://issues.redhat.com/browse/HAL-1726

[HAL-1726] Internal Error accessing EJB Runtime

---

dmr/src/main/java/org/jboss/hal/dmr/dispatch/Dispatcher.java

Issue: [HAL-1725](https://issues.redhat.com/browse/HAL-1725)

HAL-1725: include bearer token in download links when available

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/DataSourceTemplate.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/DataSourceTemplates.java
dmr/src/main/java/org/jboss/hal/dmr/ModelDescriptionConstants.java

Issue: https://issues.redhat.com/browse/HAL-1724
HAL-1724 add missiong MariaDB datasource template

HAL-1724 add missiong MariaDB datasource template

---

core/src/main/java/org/jboss/hal/core/finder/ColumnRegistry.java

Issue: [HAL-1708](https://issues.redhat.com/browse/HAL-1708)
Metadata (for security context) need to be resolved every time a column is inserted in case `{selected.host}` or other resource changed.

HAL-1708: correctly resolve metadata after server or host changes

---

app/src/main/resources/org/jboss/hal/client/configuration/subsystem/ejb/EjbView.mbui.xml

Issue: [HAL-1730](https://issues.redhat.com/browse/HAL-1730)

HAL-1730: update deprecated attribute in EJB view

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/OtherSettingsPresenter.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/OtherSettingsView.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/messaging/ClusteringView.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/messaging/ConnectionView.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/messaging/RemoteActiveMQView.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/undertow/ApplicationSecurityDomainPresenter.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/undertow/ApplicationSecurityDomainView.java
core/src/main/java/org/jboss/hal/core/elytron/CredentialReference.java
core/src/main/java/org/jboss/hal/core/mbui/ResourceElement.java

Issue: [HAL-1731](https://issues.redhat.com/browse/HAL-1731)
The reported issue is caused by `OtherSettingsView` using a custom form without validation, I've replaced the custom forms in this one and other views by the form provided by `CredentialReference`.

HAL-1731: unify credential-reference form handling

---

app/src/main/java/org/jboss/hal/client/runtime/subsystem/microprofile/health/MicroProfileHealthView.java
app/src/main/java/org/jboss/hal/client/runtime/subsystem/microprofile/health/MicroprofileHealthPreview.java
resources/src/main/java/org/jboss/hal/resources/Names.java

Issue: [HAL-1732](https://issues.redhat.com/browse/HAL-1732)

HAL-1732: fix MP-health views

---

app/package-lock.json
app/src/main/java/org/jboss/hal/client/runtime/subsystem/undertow/DeploymentPresenter.java
app/src/main/java/org/jboss/hal/client/runtime/subsystem/undertow/DeploymentView.java

https://issues.redhat.com/browse/HAL-1736

HAL-1736: Fix mixing session creation and last access time

---

ballroom/src/main/java/org/jboss/hal/ballroom/autocomplete/StringRenderer.java

https://issues.redhat.com/browse/HAL-1745

HAL-1745: Make autosuggestions HTML safe

---

app/package-lock.json
dmr/src/main/java/org/jboss/hal/dmr/ResourceAddress.java

https://issues.redhat.com/browse/HAL-1742

HAL-1742: Fix address parsing when address contains duplicate parts

---

app/package-lock.json
dmr/src/main/java/org/jboss/hal/dmr/ResourceAddress.java
dmr/src/test/java/org/jboss/hal/dmr/ResourceAddressTest.java

https://issues.redhat.com/browse/HAL-1749

HAL-1749: Fix address parsing

---

app/src/main/java/org/jboss/hal/client/runtime/server/ServerRuntimePreview.java
resources/src/main/java/org/jboss/hal/resources/Names.java

Issue: [HAL-1729](https://issues.redhat.com/browse/HAL-1729)

HAL-1729: show non-heap memory usage in server preview

---

app/src/main/java/org/jboss/hal/client/runtime/subsystem/undertow/DeploymentColumn.java

Issue: https://issues.redhat.com/browse/HAL-1750
JBEAP issue: https://issues.redhat.com/browse/JBEAP-21945
3.2.x branch PR: https://github.com/hal/console/pull/472

[HAL-1750] Fix lost address in composite operation for HC.

---

app/src/main/java/org/jboss/hal/client/patching/PatchesColumn.java

https://issues.redhat.com/browse/HAL-1722

[HAL-1722] Only latest applied patch can be rolled back

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/infinispan/Memory.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/infinispan/MemoryElement.java
dmr/src/main/java/org/jboss/hal/dmr/ModelDescriptionConstants.java
resources/src/main/java/org/jboss/hal/resources/Ids.java

prevent MissingMetadataException when viewing Infinispan/Cache Container (memory=binary|object);
prevent adding the change listener multiple times by MemoryElement.attach()

prevent MissingMetadataException when viewing Infinispan/CC

---

app/src/main/java/org/jboss/hal/client/bootstrap/endpoint/EndpointManager.java

Moved and extended error handling so that a CORS error (especially in dev mode) can be detected and reported at
- choosing a stored endpoint (management interface) in the browser;
- using the _Ping_ function when adding a new endpoint;
- using the _connect_ request parameter.
(I don't use Keycloak, so please test that, too.)
Without this modification, a CORS error causes an empty html page, even though it's meant to be handled in `BootstrapFailed`.

(CORS) error handling in EndpointManager

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/MapperDecoderPresenter.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/PermissionSetsItem.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/SimplePermissionMapperElement.java
dmr/src/main/java/org/jboss/hal/dmr/ModelDescriptionConstants.java

Issue: [HAL-1641](https://issues.redhat.com/browse/HAL-1641)

HAL-1641: add permission-sets to simple-permission-mapper view

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/wizard/ConnectionStep.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/wizard/ReviewStep.java

Issue: [HAL-1710](https://issues.redhat.com/browse/HAL-1710)

HAL-1710: provide credential reference when creating new datasource

---

app/src/main/java/org/jboss/hal/client/deployment/DeploymentPreview.java
app/src/main/java/org/jboss/hal/client/deployment/ServerGroupDeploymentPreview.java
app/src/main/java/org/jboss/hal/client/deployment/StandaloneDeploymentPreview.java
dmr/src/main/java/org/jboss/hal/dmr/ModelNode.java

Issue: [HAL-1737](https://issues.redhat.com/browse/HAL-1737)

HAL-1737: add content hash to deployment preview

---

app/src/main/java/org/jboss/hal/client/runtime/subsystem/messaging/DestinationColumn.java
app/src/main/java/org/jboss/hal/client/runtime/subsystem/messaging/DestinationPreview.java

Issue: [HAL-1625](https://issues.redhat.com/browse/HAL-1625)

HAL-1625: add pause/resume actions to JMS Topic

---

app/src/main/java/org/jboss/hal/client/runtime/host/HostPresenter.java
app/src/main/java/org/jboss/hal/client/runtime/host/HostView.java
app/src/main/java/org/jboss/hal/client/runtime/managementinterface/ConstantHeadersElement.java
app/src/main/java/org/jboss/hal/client/runtime/managementinterface/ConstantHeadersPresenter.java
app/src/main/java/org/jboss/hal/client/runtime/managementinterface/HeadersElement.java
app/src/main/java/org/jboss/hal/client/runtime/managementinterface/HttpManagementInterfaceElement.java
app/src/main/java/org/jboss/hal/client/runtime/managementinterface/HttpManagementInterfacePresenter.java
app/src/main/java/org/jboss/hal/client/runtime/server/StandaloneServerPresenter.java
app/src/main/java/org/jboss/hal/client/runtime/server/StandaloneServerView.java
dmr/src/main/java/org/jboss/hal/dmr/ModelDescriptionConstants.java
dmr/src/main/java/org/jboss/hal/dmr/ModelNodeHelper.java
resources/src/main/java/org/jboss/hal/resources/Ids.java

https://issues.redhat.com/browse/HAL-1645

HAL-1645: Manage constants headers

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/wizard/ConnectionStep.java

https://issues.redhat.com/browse/HAL-1764

HAL-1764: Re-add connection URL

---

app/package-lock.json
app/src/main/java/org/jboss/hal/client/bootstrap/endpoint/Endpoint.java
app/src/main/java/org/jboss/hal/client/bootstrap/endpoint/EndpointManager.java

https://issues.redhat.com/browse/HAL-1766

HAL-1766: Support direct connect URL for standalone mode

---

app/src/main/java/org/jboss/hal/client/runtime/subsystem/batch/BatchPreview.java
resources/src/main/java/org/jboss/hal/resources/Constants.java
resources/src/main/resources/org/jboss/hal/resources/Constants.properties
resources/src/main/resources/org/jboss/hal/resources/Constants_de.properties

https://issues.redhat.com/browse/HAL-1767

HAL-1767: Add active thread count

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/AddressTemplates.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/messaging/ServerColumn.java
dmr/src/main/java/org/jboss/hal/dmr/ModelDescriptionConstants.java

https://issues.redhat.com/browse/HAL-1772

HAL-1772: Fix adding messaging servers

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/ee/AddressTemplates.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/ee/EEPresenter.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/ee/EEView.java
dmr/src/main/java/org/jboss/hal/dmr/ModelDescriptionConstants.java
resources/src/main/java/org/jboss/hal/resources/Names.java

Issue: [HAL-1591](https://issues.redhat.com/browse/HAL-1591)
As far as I understand the EAP7 RFE only concerns this new element in the EE subsystem. It's not defined as such but for all intents and purposes `global-directory` is a singleton, so there's only the form.
(I will be on PTO next week, in case there's more)

HAL-1591: add 'global directory' to EE settings

---

core/src/main/java/org/jboss/hal/core/elytron/CredentialReference.java

Issue: [HAL-1769](https://issues.redhat.com/browse/HAL-1769)

HAL-1769: remove unneeded validation from credential reference

---

core/src/main/java/org/jboss/hal/core/ui/TuplesListItem.java

Issue: [HAL-1774](https://issues.redhat.com/browse/HAL-1774)

HAL-1774: fix handling of undefined values in tuples

---

app/src/main/java/org/jboss/hal/client/skeleton/HeaderPresenter.java
app/src/main/java/org/jboss/hal/client/skeleton/HeaderView.java
core/src/main/java/org/jboss/hal/core/header/HeaderMode.java
core/src/main/java/org/jboss/hal/core/mvp/ApplicationFinderPresenter.java
core/src/main/java/org/jboss/hal/core/mvp/ApplicationPresenter.java
core/src/main/java/org/jboss/hal/core/mvp/Refreshable.java

https://issues.redhat.com/browse/HAL-1415

[HAL-1415] Add a global refresh icon to the header

---

app/package.json

https://issues.redhat.com/browse/HAL-1784

(3.3.x) HAL-1784 Upgrade moment.js to 2.29.2

---

app/package-lock.json

https://issues.redhat.com/browse/HAL-1784

HAL-1784 package-lock.json with upgrade of moment.js to 2.29.2

---

app/package-lock.json

https://issues.redhat.com/browse/HAL-1786
upstream main branch commit https://github.com/hal/console/commit/2e50026cbea07cdf6f4acb970dfb925a449099c7

[HAL-1786] Upgrade minimist from 1.2.0 to 1.2.6

---

app/package-lock.json
app/package.json

https://issues.redhat.com/browse/HAL-1784

HAL-1784 Upgrade moment.js to 2.29.2

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/ejb/EjbView.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/remoting/RemotingPresenter.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/remoting/RemotingView.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/security/AddressTemplates.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/security/Module.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/security/SecurityDomain.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/security/SecurityDomainColumn.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/security/SecurityDomainPresenter.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/security/SecurityDomainPreview.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/security/SecurityDomainView.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/security/SecurityPresenter.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/security/SecurityView.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/undertow/HttpsListenerElement.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/undertow/ServerPresenter.java
app/src/main/java/org/jboss/hal/client/shared/sslwizard/EnableSSLWizard.java
app/src/main/resources/org/jboss/hal/client/configuration/subsystem/remoting/RemotingView.mbui.xml
app/src/main/resources/org/jboss/hal/client/configuration/subsystem/undertow/FilterView.mbui.xml
core/src/main/java/org/jboss/hal/core/PropertiesOperations.java
dmr/src/main/java/org/jboss/hal/dmr/ModelDescriptionConstants.java
resources/src/main/java/org/jboss/hal/resources/Constants.java
resources/src/main/resources/org/jboss/hal/resources/Constants.properties

https://issues.redhat.com/browse/HAL-1758

HAL-1758: Remove deprecated security code

---

CHANGELOG.md
app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/OtherSettingsPresenter.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/OtherSettingsView.java
dmr/src/main/java/org/jboss/hal/dmr/ModelDescriptionConstants.java

https://issues.redhat.com/browse/HAL-1796

HAL-1796: Fix adding elytron syslog audit resources

---

app/src/main/java/org/jboss/hal/client/bootstrap/tasks/CheckForUpdate.java

https://issues.redhat.com/browse/HAL-1781

[HAL-1781] : Enhance check for update feature

---

app/src/main/java/org/jboss/hal/client/deployment/BrowseContentElement.java
ballroom/src/main/java/org/jboss/hal/ballroom/tree/Api.java
ballroom/src/main/java/org/jboss/hal/ballroom/tree/Tree.java
resources/src/main/java/org/jboss/hal/resources/CSS.java
resources/src/main/java/org/jboss/hal/resources/Constants.java
resources/src/main/resources/org/jboss/hal/resources/Constants.properties

Issue: https://issues.redhat.com/browse/HAL-1079

[HAL-1079] Adding expand all button to show all tree in deployment detail

---

CHANGELOG.md
app/src/main/java/org/jboss/hal/client/deployment/DeploymentTasks.java
app/src/main/java/org/jboss/hal/client/deployment/StandaloneDeploymentColumn.java

https://issues.redhat.com/browse/HAL-1794

HAL-1794: Fix deployment wizard for failed deployments

---

app/package-lock.json
app/package.json

Issue: https://issues.redhat.com/browse/HAL-1799
Fix downstream JBEAP issue https://issues.redhat.com/browse/JBEAP-23828
main branch is upgraded via https://github.com/hal/console/pull/650
@hpehl please review

HAL-1799 Upgrade moment.js to 2.29.4

---

CHANGELOG.md
app/src/main/java/org/jboss/hal/client/bootstrap/tasks/FindDomainController.java
app/src/main/java/org/jboss/hal/client/patching/HostPatchesPreview.java
config/src/main/java/org/jboss/hal/config/AbstractEnvironment.java
config/src/main/java/org/jboss/hal/config/Environment.java
core/src/main/java/org/jboss/hal/core/runtime/TopologyTasks.java
core/src/main/java/org/jboss/hal/core/runtime/host/Host.java
dmr/src/main/java/org/jboss/hal/dmr/ModelDescriptionConstants.java

https://issues.redhat.com/browse/HAL-1800

HAL-1800: Fix broken bootstrap for WildFly < 27

---

app/src/main/java/org/jboss/hal/client/deployment/StandaloneDeploymentColumn.java
resources/src/main/java/org/jboss/hal/resources/Messages.java
resources/src/main/resources/org/jboss/hal/resources/Messages.properties

Issue: https://issues.redhat.com/browse/HAL-1425

[HAL-1425] checking if data source is available

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/DataSourceTemplates.java

https://issues.redhat.com/browse/HAL-1656

[HAL-1656] Driver-XA classes should not be hardcoded in console code

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/DataSourceTemplates.java

Issue Link: https://issues.redhat.com/browse/HAL-1815

[HAL-1815] Hardcoded database name in CONNECTION_URL should be replaced by a generic name

---

app/package-lock.json
app/package.json

https://issues.redhat.com/browse/JBEAP-24267

JBEAP-24267: Upgrade jQuery to 3.6.1

---

app/package-lock.json
app/package.json
app/src/web/script/index.js

https://issues.redhat.com/browse/HAL-1819

HAL-1819: Fix dataTables init code

---

README.md

Sorry but LOL, a new typo to add to the WildFly misspellings database :-)

Typo fix in README.md.

---

core/src/main/java/org/jboss/hal/core/runtime/TopologyTasks.java

https://issues.redhat.com/browse/HAL-1822

[HAL-1822] TopologyTasks.RunningServers uses invalid resource addresses

---

CHANGELOG.md
app/package-lock.json
app/src/main/java/org/jboss/hal/client/configuration/subsystem/logging/LoggingProfileView.java
app/src/main/resources/org/jboss/hal/client/configuration/subsystem/logging/LoggingProfileView.mbui.xml
app/src/main/resources/org/jboss/hal/client/configuration/subsystem/logging/LoggingView.mbui.xml
ballroom/src/main/java/org/jboss/hal/ballroom/form/AbstractForm.java
ballroom/src/main/java/org/jboss/hal/ballroom/form/DataMapping.java
ballroom/src/main/java/org/jboss/hal/ballroom/form/DefaultMapping.java
core/src/main/java/org/jboss/hal/core/mbui/dialog/AddResourceDialog.java
core/src/main/java/org/jboss/hal/core/mbui/form/ModelNodeForm.java
core/src/main/java/org/jboss/hal/core/mbui/form/ModelNodeMapping.java
core/src/main/java/org/jboss/hal/core/ui/FileFormItem.java
dmr/src/main/java/org/jboss/hal/dmr/ModelNodeHelper.java
dmr/src/test/java/org/jboss/hal/dmr/ModelNodeHelperTest.java
meta/src/main/java/org/jboss/hal/meta/Metadata.java
resources/src/main/java/org/jboss/hal/resources/Names.java

https://issues.redhat.com/browse/HAL-1826

HAL-1826: Support nested attributes in MBUI views

---

app/package-lock.json
app/src/main/java/org/jboss/hal/client/ConsoleModule.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/undertow/HostColumn.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/undertow/HostPresenter.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/undertow/HostPreview.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/undertow/HostSetting.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/undertow/HostView.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/undertow/ServerColumn.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/undertow/ServerPresenter.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/undertow/ServerView.java
dmr/src/main/java/org/jboss/hal/dmr/ModelDescriptionConstants.java
meta/src/main/java/org/jboss/hal/meta/token/NameTokens.java
resources/src/main/java/org/jboss/hal/resources/Constants.java
resources/src/main/java/org/jboss/hal/resources/Ids.java
resources/src/main/java/org/jboss/hal/resources/Names.java
resources/src/main/resources/org/jboss/hal/resources/Constants.properties

https://issues.redhat.com/browse/HAL-1600
Please note that this RFE has yet to be fully implemented.
The feature has been partially implemented but is inactive in the console.

HAL-1600: Partial, inactive implementation

---

app/src/less/wizard.less
app/src/main/java/org/jboss/hal/client/deployment/AbstractDeploymentColumn.java
app/src/main/java/org/jboss/hal/client/deployment/BrowseContentPresenter.java
app/src/main/java/org/jboss/hal/client/deployment/BrowseContentView.java
app/src/main/java/org/jboss/hal/client/deployment/ContentColumn.java
app/src/main/java/org/jboss/hal/client/deployment/DeploymentTasks.java
app/src/main/java/org/jboss/hal/client/deployment/ServerGroupDeploymentColumn.java
app/src/main/java/org/jboss/hal/client/deployment/ServerGroupDeploymentPresenter.java
app/src/main/java/org/jboss/hal/client/deployment/ServerGroupDeploymentPreview.java
app/src/main/java/org/jboss/hal/client/deployment/StandaloneDeploymentColumn.java
ballroom/src/main/java/org/jboss/hal/ballroom/wizard/Wizard.java
core/src/main/java/org/jboss/hal/core/deployment/Content.java
core/src/main/java/org/jboss/hal/core/deployment/Deployment.java
core/src/main/java/org/jboss/hal/core/deployment/ServerGroupDeployment.java
flow/src/main/java/org/jboss/hal/flow/FlowContext.java
resources/src/main/java/org/jboss/hal/resources/CSS.java
resources/src/main/java/org/jboss/hal/resources/Messages.java
resources/src/main/resources/org/jboss/hal/resources/Messages.properties

Issue: [HAL-1824](https://issues.redhat.com/browse/HAL-1824) / [JBEAP-24440](https://issues.redhat.com/browse/JBEAP-24440)
This is a port of #810

HAL-1824: add a confirmation check for replacing deployments

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/logging/LoggingProfileView.java
app/src/main/resources/org/jboss/hal/client/configuration/subsystem/logging/LoggingProfileView.mbui.xml
app/src/main/resources/org/jboss/hal/client/configuration/subsystem/logging/LoggingView.mbui.xml
ballroom/src/main/java/org/jboss/hal/ballroom/form/AbstractForm.java
ballroom/src/main/java/org/jboss/hal/ballroom/form/DataMapping.java
ballroom/src/main/java/org/jboss/hal/ballroom/form/DefaultMapping.java
core/src/main/java/org/jboss/hal/core/mbui/dialog/AddResourceDialog.java
core/src/main/java/org/jboss/hal/core/mbui/form/ModelNodeForm.java
core/src/main/java/org/jboss/hal/core/mbui/form/ModelNodeMapping.java
core/src/main/java/org/jboss/hal/core/ui/FileFormItem.java
dmr/src/main/java/org/jboss/hal/dmr/ModelNodeHelper.java
dmr/src/test/java/org/jboss/hal/dmr/ModelNodeHelperTest.java
meta/src/main/java/org/jboss/hal/meta/Metadata.java
resources/src/main/java/org/jboss/hal/resources/Names.java

HAL issue: https://issues.redhat.com/browse/HAL-1835
EAP issue: https://issues.redhat.com/browse/JBEAP-24482
Upstream PR: https://github.com/hal/console/pull/781

[JBEAP-24482][HAL-1835] Backport of HAL-1826: Support nested attributes in MBUI views

---

app/src/main/java/org/jboss/hal/client/runtime/subsystem/datasource/DataSourceColumn.java
app/src/main/java/org/jboss/hal/client/runtime/subsystem/datasource/DataSourcePreview.java
core/src/main/java/org/jboss/hal/core/datasource/DataSource.java

Issue: [HAL-1848](https://issues.redhat.com/browse/HAL-1848)

HAL-1848: fix datasource statistics checks

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/JdbcDriverColumn.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/wizard/DriverStep.java

Issue: [HAL-1847](https://issues.redhat.com/browse/HAL-1847)
The attribute will become deprecated in the next release, the PR is already merged.

HAL-1847: fix JDBC driver forms following driver-name deprecation

---

app/src/main/java/org/jboss/hal/client/bootstrap/endpoint/EndpointManager.java

https://issues.redhat.com/browse/HAL-1804
Test for accessing the console still need to be added to https://github.com/hal/testsuite.next.

[HAL-1804] Update the OIDC integration to check the /oidc endpoint instead of the /keycloak/adapter endpoint

---

app/src/main/java/org/jboss/hal/client/runtime/subsystem/ejb/EjbColumn.java

Issue: https://issues.redhat.com/browse/JBEAP-21969
Upstream Issue: https://issues.redhat.com/browse/HAL-1726
Upstream PR: https://github.com/hal/console/pull/443

[JBEAP-21969,HAL-1726] Internal Error accessing EJB Runtime

---

config/src/main/java/org/jboss/hal/config/Role.java
core/src/main/java/org/jboss/hal/core/accesscontrol/AccessControl.java

https://issues.redhat.com/browse/HAL-1866

HAL-1866: Switch role comparison to be case-insensitive

---

core/src/main/java/org/jboss/hal/core/modelbrowser/ReadChildren.java

Issue: [HAL-1872](https://issues.redhat.com/browse/HAL-1872)
Port of #914

HAL-1872: fix id generation in Model Browser

---

core/src/main/java/org/jboss/hal/core/modelbrowser/ModelBrowser.java
resources/src/main/java/org/jboss/hal/resources/Constants.java
resources/src/main/resources/org/jboss/hal/resources/Constants.properties

https://issues.redhat.com/browse/HAL-1871
EAP 8 issue: https://issues.redhat.com/browse/JBEAP-25155

HAL-1871 Make ModelBrowser able to process resources that has their own "name" field

---

app/package-lock.json

https://issues.redhat.com/browse/HAL-1875

HAL-1875: Upgrade tough-cookie to 4.1.3

---

app/package-lock.json
app/package.json

https://issues.redhat.com/browse/HAL-1880 
Downstream JBEAP: https://issues.redhat.com/browse/JBEAP-25187

[HAL-1880] Upgrade semver to 7.5.4.

---

core/src/main/java/org/jboss/hal/core/mbui/form/ModelNodeMapping.java

Issue: https://issues.redhat.com/browse/HAL-1884 Fix unnested attributes handle in MBUI views

[HAL-1884] Fix unnested attributes handle in MBUI views

---

app/src/main/java/org/jboss/hal/client/deployment/AbstractDeploymentColumn.java

Jira - https://issues.redhat.com/browse/EAPSUP-1306  
It seems to be an unintentional change because of this [JBEAP-24440](https://issues.redhat.com/browse/JBEAP-24440) ,hence I changed the "remove()" with "undeploy()".

EAPSUP-1306

---

app/src/main/java/org/jboss/hal/client/deployment/AbstractDeploymentColumn.java

Issue: https://issues.redhat.com/browse/HAL-1908
Upstream PR: https://github.com/hal/console/pull/963

HAL-1908 Fix ITEM_REMOVE_ACTION title

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/undertow/HostSetting.java
app/src/main/java/org/jboss/hal/client/configuration/subsystem/undertow/HostView.java
resources/src/main/java/org/jboss/hal/resources/Ids.java

Issue: [HAL-1929](https://issues.redhat.com/browse/HAL-1929)

HAL-1929: remove single-sign-on from Undertow host

---

app/src/main/java/org/jboss/hal/client/skeleton/HeaderView.java
resources/src/main/java/org/jboss/hal/resources/Ids.java

Issue: [HAL-1945](https://issues.redhat.com/browse/HAL-1945)

HAL-1945: fix notification badge visibility

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/undertow/ApplicationSecurityDomainPresenter.java

Issue: [HAL-1949](https://issues.redhat.com/browse/HAL-1949)

HAL-1949: correct SSO address templates

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/DataSourceTemplates.java

JIra: https://issues.redhat.com/browse/HAL-1960

[HAL-1960] Mark variable parts in attributes in the DB wizards

---

CHANGELOG.md
app/src/main/java/org/jboss/hal/client/installer/RevertWizard.java
app/src/main/java/org/jboss/hal/client/installer/UpdateColumn.java
app/src/main/java/org/jboss/hal/client/installer/UpdateOfflineWizard.java
app/src/main/java/org/jboss/hal/client/installer/UpdateOnlineWizard.java
app/src/main/java/org/jboss/hal/client/installer/UploadArchivesStep.java
dmr/src/main/java/org/jboss/hal/dmr/ModelDescriptionConstants.java

https://issues.redhat.com/browse/HAL-1963

HAL-1963: Make --no-resolve-local-cache the default

---

meta/src/main/java/org/jboss/hal/meta/AddressTemplate.java
meta/src/test/java/org/jboss/hal/meta/processing/LookupResultTest.java
meta/src/test/java/org/jboss/hal/meta/security/ConstraintTest.java
meta/src/test/java/org/jboss/hal/meta/security/ConstraintsTest.java

Ticket: https://issues.redhat.com/browse/HAL-1906
Upstream PR: https://github.com/hal/console/pull/1037

[HAL-1906][3.3.x] allow path serparator to be part of KVP

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/microprofile/AddConfigSourceWizard.java

https://issues.redhat.com/browse/HAL-1969

HAL-1969: Mark name as required

---

ballroom/src/main/java/org/jboss/hal/ballroom/form/TagsManager.java

Issue: [HAL-1967](https://issues.redhat.com/browse/HAL-1967)

HAL-1967: fix tag removal

---

app/src/main/java/org/jboss/hal/client/deployment/AbstractDeploymentColumn.java

Issue: https://issues.redhat.com/browse/HAL-1957 
HAL-1957 fix remove action labels
3.3.x branch https://github.com/hal/console/pull/1095
3.6.x branch https://github.com/hal/console/pull/1096

HAL-1957 fix remove action labels

---

app/src/main/java/org/jboss/hal/client/ConsoleModule.java
app/src/main/java/org/jboss/hal/client/runtime/subsystem/datasource/DataSourceColumn.java
app/src/main/java/org/jboss/hal/client/runtime/subsystem/datasource/DataSourceXAPresenter.java
app/src/main/java/org/jboss/hal/client/runtime/subsystem/datasource/DataSourceXAView.java
meta/src/main/java/org/jboss/hal/meta/token/NameTokens.java

https://issues.redhat.com/browse/HAL-1970

HAL-1970: Split runtime ds presenter/view into xa and non-xa version

---

app/package-lock.json
app/package.json

https://issues.redhat.com/browse/HAL-1965 
HAL-1965 Upgrade datatables.net to ^1.11.3
This is an alternative of #1057

HAL-1965 Upgrade datatables.net to ^1.11.3

---

app/src/main/java/org/jboss/hal/client/accesscontrol/AccessControlTokens.java
app/src/main/java/org/jboss/hal/client/deployment/BrowseByColumn.java
app/src/main/java/org/jboss/hal/client/deployment/ServerGroupDeploymentPreview.java
app/src/main/java/org/jboss/hal/client/homepage/TourSetup.java
core/src/main/java/org/jboss/hal/core/finder/FinderPathFactory.java
resources/src/main/java/org/jboss/hal/resources/Names.java

HAL-1984: fix id generation from proprietary strings

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/JdbcRealmElement.java

Issue: https://issues.redhat.com/browse/JBEAP-28352
Upstream issue: https://issues.redhat.com/browse/HAL-1987
Upstream PR: https://github.com/hal/console/pull/1212

HAL-1987 fix JDBC realm form ping

---

wildfly/src/main/docker/Dockerfile-domain
wildfly/src/main/docker/Dockerfile-domain-development

https://issues.redhat.com/browse/HAL-1993
Related to https://github.com/hal/manatoko/pull/234

[HAL-1993] Use SASL authentication in tests for domain

---

core/src/main/java/org/jboss/hal/core/subsystem/Subsystems.java

Issue: https://issues.redhat.com/browse/JBEAP-28484
Upstream is fixed since 3.4.0.Final.
upstream commit https://github.com/hal/console/commit/93de6c7513fe5fd60a455dc6fc3e040bf30b645e

[JBEAP-28484] fix Elytron subsystem metadata.

---

app/package-lock.json

Issue: https://issues.redhat.com/browse/HAL-1997

[HAL-1997] [3.2.x] Upgrade minimist from 1.2.0 to 1.2.6

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/DataSourceTemplates.java

HAL-1996: fix placeholder value handling

---

ballroom/src/main/java/org/jboss/hal/ballroom/chart/Utilization.java

https://issues.redhat.com/browse/HAL-2007

HAL-2007: Fix utilization bar if current > total

---

app/src/main/java/org/jboss/hal/client/runtime/managementoperations/ManagementOperationsPresenter.java

Backport of 2a5fd22d3c14bf00ffb6ac45de5ed94c8fde351e to EAP 8 branch

[HAL-2004] Fix malformed address template

---

meta/src/main/java/org/jboss/hal/meta/description/ResourceDescription.java

https://issues.redhat.com/browse/JBEAP-29192
https://issues.redhat.com/browse/JBEAP-29195

[JBEAP-29192, JBEAP-29195] Can not add unmanaged deployment

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/OtherSettingsView.java
dmr/src/main/java/org/jboss/hal/dmr/ModelDescriptionConstants.java

https://issues.redhat.com/browse/HAL-2014

HAL-2014: Optional fields missing in the Add Realms form

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/OtherSettingsView.java
dmr/src/main/java/org/jboss/hal/dmr/ModelDescriptionConstants.java

https://issues.redhat.com/browse/JBEAP-29201

JBEAP-29201: Optional fields missing in the Add Realms form

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/FactoriesView.java
dmr/src/main/java/org/jboss/hal/dmr/ModelDescriptionConstants.java

https://issues.redhat.com/browse/HAL-2015

HAL-2015: Enabling missing in the Add Filters pop-up

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/FactoriesView.java
dmr/src/main/java/org/jboss/hal/dmr/ModelDescriptionConstants.java

https://issues.redhat.com/browse/JBEAP-29202

JBEAP-29202: Enabling missing in the Add Filters pop-up

---

app/src/main/java/org/jboss/hal/client/runtime/subsystem/datasource/DataSourceView.java
app/src/main/java/org/jboss/hal/client/runtime/subsystem/datasource/DataSourceXAView.java
app/src/main/java/org/jboss/hal/client/runtime/subsystem/resourceadapter/BaseView.java

Issue: [HAL-2010](https://issues.redhat.com/browse/HAL-2010)
Depends on #1304 so I'm making this a draft, the RA view was based on the DS view and has the same problem.

HAL-2010: fix runtime view updating

---

app/package-lock.json
app/package.json

Issue link: https://issues.redhat.com/browse/HAL-2016

(3.2.x) HAL-1784 Upgrade moment.js from 2.24.0 to 2.29.2

---

ballroom/src/main/java/org/jboss/hal/ballroom/chart/Utilization.java

https://issues.redhat.com/browse/HAL-2007
https://issues.redhat.com/browse/JBEAP-29902
upstream PR: https://github.com/hal/console/pull/1297
[Backport [HAL-2007](https://issues.redhat.com/browse/HAL-2007) fix to downstream 3.6 branch]

[HAL-2007] Fix utilization bar

---

core/src/main/java/org/jboss/hal/core/mbui/form/FormHelper.java

HAL-2017: avoid resetting nested attributes

---

app/src/main/java/org/jboss/hal/client/configuration/subsystem/batch/BatchView.java
app/src/main/resources/org/jboss/hal/client/configuration/subsystem/batch/BatchView.mbui.xml

https://issues.redhat.com/browse/HAL-1962

HAL-1962: Include 'execution-records-limit' attribute

---

wildfly/src/main/docker/Dockerfile-domain-development
wildfly/src/main/docker/Dockerfile-standalone-development

https://github.com/hpehl/wado/issues/7

build development images based on the openjdk:17-alpine image

---

core/src/main/java/org/jboss/hal/core/OperationFactory.java

https://issues.redhat.com/browse/HAL-2026

HAL-2026: Refactor undefine-attribute operation rules
