hal/console

- app/src/main/java/org/jboss/hal/client/configuration/subsystem/infinispan/CacheContainerPresenter.java
- dmr/src/main/java/org/jboss/hal/dmr/ModelDescriptionConstants.java
Fix for Infinispan cache store handling, adding a store requires the `allow-resource-service-restart` header (with the exception of file store but that seems to be a bug).
Also fixing the `reload` method, fetching selected profile fails in standalone mode.
> fix Infinispan cache store handling

- ballroom/src/main/java/org/jboss/hal/ballroom/autocomplete/AutoComplete.java
- ballroom/src/main/java/org/jboss/hal/ballroom/autocomplete/Options.java
Autocomplete is broken in a Wizard (e.g. the Driver step in a Datasource Wizard). The JS component uses `document.querySelectorAll` to find the input but doesn't work because the element isn't part of the DOM yet. Wizard is inserting the elements after all Attachables have been attached.
This might a be problem for other components but I haven't checked.
> Fix autocomplete intialization

- ballroom/src/main/java/org/jboss/hal/ballroom/form/NumberItem.java
NumberItem with non-numerical value shouldn't return `isEmpty() == true`. The current behavior makes it fail RequiredValidation and pass NumberValidation, it should behave the opposite way.
> fix NumberItem validation

- app/src/main/java/org/jboss/hal/client/deployment/BrowseContentElement.java
- app/src/main/java/org/jboss/hal/client/patching/wizard/ApplyPatchWizard.java
- app/src/main/java/org/jboss/hal/client/patching/wizard/RollbackWizard.java
- core/src/main/java/org/jboss/hal/core/expression/ExpressionResolver.java
- core/src/main/java/org/jboss/hal/core/runtime/group/ServerGroupActions.java
- core/src/main/java/org/jboss/hal/core/runtime/host/HostActions.java
- core/src/main/java/org/jboss/hal/core/runtime/server/ServerActions.java
- dmr/src/main/java/org/jboss/hal/dmr/dispatch/Dispatcher.java
- dmr/src/main/java/org/jboss/hal/dmr/dispatch/ExceptionalFlowCallback.java
- dmr/src/main/java/org/jboss/hal/dmr/dispatch/FailedFlowCallback.java
See commit messages. The OnError and OnFailure renaming were pretty unnecessary, but it makes all method definition to enter in one line 😉. And all those callbacks should be removed eventually.
> Minor changes on Dispatcher to see if it matches RX success/error

- app/src/main/java/org/jboss/hal/client/skeleton/HeaderPresenter.java
- app/src/main/java/org/jboss/hal/client/skeleton/HeaderView.java
- app/src/main/java/org/jboss/hal/client/skeleton/MessageSink.java
In notification drawer the "clear message" button is inside the message area so it counts as a message and when you click it it removes itself.
As for the second commit it seems to me there isn't a clear separation of concerns between the MessageSink and the presenter/view - the clear button would call the presenter which would then call the MessageSink instead of the MessageSink simply notifying the presenter that messages have been cleared. I've also added handling for removing single messages.
> Clear message fix

- app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/DataSourceColumn.java
- app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/wizard/DriverStep.java
- app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/wizard/NamesStep.java
- app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/wizard/TestStep.java
- ballroom/src/main/java/org/jboss/hal/ballroom/form/PatternValidation.java
- resources/src/main/java/org/jboss/hal/resources/Messages.java
- resources/src/main/resources/org/jboss/hal/resources/Messages.properties
Added validation to the datasource wizard - JNDI name has to begin with "java:/" or "java:jboss/" and Driver name has to correspond to an existing driver.
Fixed "Test connection" in the wizard and in the datasource menu - it was only working in domain and only for non-XA datasources.
> Datasource validation

- app/src/main/java/org/jboss/hal/client/configuration/subsystem/transaction/TransactionPresenter.java
- app/src/main/java/org/jboss/hal/client/configuration/subsystem/transaction/TransactionView.java
- app/src/main/resources/org/jboss/hal/client/configuration/subsystem/transaction/TransactionView.mbui.xml
- core/src/main/java/org/jboss/hal/core/OperationFactory.java
- core/src/main/java/org/jboss/hal/core/mbui/form/ExactlyOneAlternativeValidation.java
- core/src/main/java/org/jboss/hal/core/mbui/form/RequiredByValidation.java
- dmr/src/main/java/org/jboss/hal/dmr/ModelDescriptionConstants.java
https://issues.jboss.org/browse/HAL-1454
* Removed the custom validation and save operations in TransactionPresenter, to use the default validation and save of ModelNodeForm, as the resource description contains the alternatives and requires metadata.
* Enhanced the validation code to consider the SwitchItem false value.
* Enhanced the OperationFactory.reset operation to consider the "requires" metadata
> HAL-1454 Unable to edit Transaction's Process ID Socket Max Ports

- app/src/main/java/org/jboss/hal/client/runtime/subsystem/elytron/ElytronColumn.java
- app/src/main/java/org/jboss/hal/client/runtime/subsystem/elytron/IdentityAttributeItem.java
- app/src/main/java/org/jboss/hal/client/runtime/subsystem/elytron/RealmsPresenter.java
- app/src/main/java/org/jboss/hal/client/shared/sslwizard/EnableSSLWizard.java
- app/src/main/resources/org/jboss/hal/client/configuration/subsystem/logging/LoggingProfileView.mbui.xml
- ballroom/src/main/java/org/jboss/hal/ballroom/form/TagsManager.java
- resources/src/main/resources/org/jboss/hal/resources/Messages.properties
- resources/src/main/resources/org/jboss/hal/resources/Messages_pt_BR.properties
HAL-1469 Unable to read or edit categories in logging profile
https://issues.jboss.org/browse/HAL-1469
HAL-1470 add-identity in filesystem-realm with no notification
https://issues.jboss.org/browse/HAL-1470
* Due to ListItem having problems to use the semicolon as delimiter, reverted the tags delimiter to comma and replace the value delimiter of IdentityAttributeItem from colon to semicolon
* Fixed the ElytronColumn finder selector
> Fix logging profile form, add-identity with attributes

- app/src/less/wizard.less
- ballroom/src/main/java/org/jboss/hal/ballroom/wizard/Wizard.java
- resources/src/main/java/org/jboss/hal/resources/CSS.java
https://issues.jboss.org/browse/HAL-1482
* patternfly introduced a change in its wizard.less file
* Also increased the line-height of the wizard steps, as some letters had the lower part hidden
> HAL-1482 Broken CSS for steps in wizard header

- docker/pom.xml
- docker/src/main/docker/hal-wildfly-nightly/Dockerfile
- docker/src/main/docker/hal-wildfly-nightly/module.xml
- docker/src/main/docker/hal-wildfly-nightly/setup.sh
This PR automizes creation of a WF with the latest HAL in a form of Docker image. This image additionally to the [``hal-wildfly``](https://hub.docker.com/r/halconsole/hal-wildfly/) image brings insecure domain configuration ``host-insecure.xml`` for testing purposes. To boot WF in domain mode without administration simply issue following command:
``docker run -p 8080:8080 -p 9990:9990 halconsole/hal-wildfly-nightly /opt/jboss/wildfly/bin/domain.sh --host-config host-insecure.xml -b 0.0.0.0 -bmanagement 0.0.0.0``. 
When building the Docker image, the [latest WF nightly build](https://ci.wildfly.org/viewType.html?buildTypeId=WF_Nightly) is being pulled and processed furthemore. The download of this artifact is slowing down the build process. To reduce this speedbump a build hook could be an …
> HAL & WildFly nightly Docker image

- app/src/main/java/org/jboss/hal/client/deployment/ServerGroupDeploymentColumn.java
- app/src/main/java/org/jboss/hal/client/deployment/StandaloneDeploymentColumn.java
- app/src/main/java/org/jboss/hal/client/runtime/subsystem/logging/LogFile.java
- app/src/main/java/org/jboss/hal/client/runtime/subsystem/logging/LogFileColumn.java
- ballroom/src/main/java/org/jboss/hal/ballroom/LabelBuilder.java
- ballroom/src/main/java/org/jboss/hal/ballroom/table/ColumnBuilder.java
* HAL-1485 Replace 'list-log-files' with using the 'log-file' resource
https://issues.jboss.org/browse/HAL-1485
* HAL-1519 Undeploy operation wording is not unified
https://issues.jboss.org/browse/HAL-1519
* Only escapes html in the Datatable column if the value is not null
> Replace 'list-log-files' with using the 'log-file' resource and other fixes

- app/src/main/java/org/jboss/hal/client/configuration/subsystem/infinispan/MemoryElement.java
- app/src/main/java/org/jboss/hal/client/configuration/subsystem/infinispan/StoreElement.java
https://issues.jboss.org/browse/HAL-1627
> HAL-1627: Fix store and memory element

- app/src/main/java/org/jboss/hal/client/configuration/subsystem/messaging/ServerSettingsColumn.java
- app/src/main/java/org/jboss/hal/client/runtime/subsystem/messaging/DestinationColumn.java
https://issues.jboss.org/browse/HAL-1639
Id is converted to the lowercase, due to which the server name was set incorrectly.
> HAL-1639: Console does not display destination list, if the messaging server name is in caps

- dmr/src/main/java/org/jboss/hal/dmr/dispatch/Dispatcher.java
(cherry picked from commit efdd2a43cb7ab3de2465e44c80a01e02cf102140)
issue: https://issues.jboss.org/browse/JBEAP-17576
upstream is fixed since 3.2.1
**One more question**: I don't see issue number for commit "DMR operations use always POST" not sure if there any prerequisite to pick it up ?
> DMR operations use always POST

- app/src/main/java/org/jboss/hal/client/deployment/StandaloneDeploymentColumn.java
- resources/src/main/java/org/jboss/hal/resources/Constants.java
- resources/src/main/java/org/jboss/hal/resources/Messages.java
- resources/src/main/resources/org/jboss/hal/resources/Constants.properties
- resources/src/main/resources/org/jboss/hal/resources/Messages.properties
It's a bit convoluted but this works.
Added a button to explode all subdeployments (this can only be done while the deployment is enabled and exploded), I don't know if there's a use case to explode each them separately. The only problem is that there's no way to tell if the subdeployments are exploded, so if the user tries the operation again we'll show an error - added a custom message since the default isn't very clear.
> HAL-1634: implement subdeployment exploding

- ballroom/src/main/java/org/jboss/hal/ballroom/form/TagsItem.java
Component issue: https://issues.jboss.org/browse/HAL-1647
TagsItem registers it's api.onAdded() callback inside the attach() method, which leads to the callback being registered multiple times (every time the component is attached). As a result, the JVM options field value is saved multiple times.
> HAL-1647 JVM option is saved multiple times

- app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/ElytronColumn.java
- app/src/main/java/org/jboss/hal/client/configuration/subsystem/messaging/MessagingCategoryColumn.java
- app/src/main/java/org/jboss/hal/client/configuration/subsystem/undertow/UndertowSettingsColumn.java
- app/src/main/java/org/jboss/hal/client/runtime/subsystem/elytron/ElytronColumn.java
Component issue: https://issues.jboss.org/browse/HAL-1646
EAP 7.2 issue: https://issues.jboss.org/browse/JBEAP-18118
Upstream issue: https://issues.jboss.org/browse/JBEAP-18157
Upstream PR: https://github.com/hal/console/pull/350
In certain ConfigurationColumns, list of menu items was created in a wrong scope - directly in a column constructor. Those menu items were then permanently linked to the profile selected when the column was created, even when user later selected different profile.
The items should rather be generated by an ItemsProvider, which will cause the items to be regenerated every time the column is displayed, so they will always link to a currently selected profile.
> HAL-1646 Navigation doesn't remember chosen profile in some subsystems

- app/src/main/java/org/jboss/hal/client/runtime/configurationchanges/ConfigurationChangesPresenter.java
Issue: [HAL-1621](https://issues.redhat.com/browse/HAL-1621)
The issue itself is dependent on #355 (i.e. the command might still not be available when RBAC is enabled) but this PR fixes the general problem.
> HAL-1621: fix configuration-changes constrains

- app/src/main/java/org/jboss/hal/client/runtime/BrowseByColumn.java
- app/src/main/java/org/jboss/hal/client/runtime/configurationchanges/ConfigurationChangesPresenter.java
- app/src/main/java/org/jboss/hal/client/runtime/host/AddressTemplates.java
- app/src/main/java/org/jboss/hal/client/runtime/host/HostColumn.java
- app/src/main/java/org/jboss/hal/client/runtime/host/HostPresenter.java
- app/src/main/java/org/jboss/hal/client/runtime/server/ServerColumn.java
Issue: [HAL-1640](https://issues.redhat.com/browse/HAL-1640)
I have replaced most instances of `{domain.controller}` with `{host=*}`, since that only worked for master host controller. I have also replaced some instances of `{selected.host}` with `{host=*}` since they were used in places where no host has been selected yet (and so the wildcard was resolving to nothing).
> HAL-1640: fix the scope of host-related meatadata requirements

- core/src/main/java/org/jboss/hal/core/mbui/form/ModelNodeForm.java
Issue: [HAL-1602](https://issues.jboss.org/browse/HAL-1602)
changed the failure outcome to show READONLY instead, in cases without a table the EMPTY gets shown because of `form.view(model)`
> HAL-1602: do not show empty form state when nothing is selected

- app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/DataSourceTemplates.java
Mysql Driver class is pointing to wrong class,since the class's package structure as changed since mysql connector J/8
> Fix for HAL-1655

- app/src/main/java/org/jboss/hal/client/runtime/subsystem/ejb/EjbColumn.java
Issue: [HAL-1658](https://issues.redhat.com/browse/HAL-1658)
Since the results of composite operations differ between master and slave it seems better to just strip the host/server part and then append the result to it.
This shouldn't be affecting other subsystems, I haven't found any where composite is used with `read-resource`.
> HAL-1658: fix address handling in composite operation

- app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/CustomListItem.java
Issue: [HAL-1648](https://issues.redhat.com/browse/HAL-1648)
Changed the `value` node in `CustomListItem` to be treated as Int, the item is currently only used in JDBC realm so this does not affect other forms.
> HAL-1648: ensure proper type conversion

- app/src/main/java/org/jboss/hal/client/runtime/BrowseByColumn.java
- app/src/main/java/org/jboss/hal/client/runtime/configurationchanges/ConfigurationChangesPresenter.java
- app/src/main/java/org/jboss/hal/client/runtime/host/AddressTemplates.java
- app/src/main/java/org/jboss/hal/client/runtime/host/HostColumn.java
- app/src/main/java/org/jboss/hal/client/runtime/host/HostPresenter.java
- app/src/main/java/org/jboss/hal/client/runtime/server/ServerColumn.java
- meta/src/main/java/org/jboss/hal/meta/AddressTemplate.java
Backport HAL-1640 to 3.0.x stream. This PR also fixes HAL-1651.
Component jira: https://issues.redhat.com/browse/HAL-1651
EAP 7.2.x jira: https://issues.redhat.com/browse/JBEAP-18012
Upstream commit: https://github.com/hal/console/commit/83ff6ada8a914a98b2024fd88e758d57ef2bda7c
> HAL-1640, HAL-1651 fix the scope of host-related meatadata requirements

- core/src/main/java/org/jboss/hal/core/mbui/form/ModelNodeForm.java
- core/src/main/java/org/jboss/hal/core/modelbrowser/ModelBrowser.java
- core/src/main/java/org/jboss/hal/core/modelbrowser/ResourcePanel.java
Issue: [HAL-1669](https://issues.redhat.com/browse/HAL-1669)
Related: [JBEAP-18368](https://issues.redhat.com/browse/JBEAP-18368)
The idea is this:
When adding a new resource:
- if there are required Object attributes (in OPERATIONS / ADD / REQUEST_PROPERTIES) take their nested attributes and put them on the same level as the primary attributes, change their name to "parent.attribute" (unfortunately in the case of Keycloak they'll still be hidden under Optional attributes)
- when retrieving the form create the object based on those names
When editing a resource
- same thing, put nested attributes on the same level as other attributes
- when the form is saved we don't have to do anything because CLI `write-attribute` supports the "parent.attribute" format
> HAL-1669: add object attribute support to model browser

- app/src/main/java/org/jboss/hal/client/bootstrap/tasks/ReadAuthentication.java
https://issues.redhat.com/browse/HAL-1677  fix for possible undefined host element for host-scoped-role
WFCORE reference issue https://issues.redhat.com/browse/WFCORE-4882 discussed that an undefined host element for host-scoped-roles allowed.
downstream 3.0.x branch PR: https://github.com/hal/console/pull/390
> HAL-1677 fix for possible undefined host element for host-scoped-role

- app/src/main/java/org/jboss/hal/client/runtime/subsystem/messaging/JmsQueuePresenter.java
(cherry picked from commit 0ec5ecef18620d5e649917dab6c7227503865caa)
issue: https://issues.redhat.com/browse/HAL-1682
JBEAP issue: https://issues.redhat.com/browse/JBEAP-19236
The op name for move-message and move-messages are wrong.
upstream PR: https://github.com/hal/console/pull/396
> HAL-1682 fix wrong op name for message moving

- app/src/main/java/org/jboss/hal/client/configuration/subsystem/SubsystemColumn.java
Issue: [HAL-1633](https://issues.redhat.com/browse/HAL-1633)
Since the subsystem doesn't contain any children or complex attributes I didn't add a dedicated view, the model browser can handle it.
> HAL-1633: enable JAXRS subsystem

- app/src/less/hal.less
- app/src/main/java/org/jboss/hal/client/runtime/subsystem/undertow/DeploymentPreview.java
- ballroom/src/main/java/org/jboss/hal/ballroom/chart/Donut.java
Issue: [HAL-1704](https://issues.redhat.com/browse/HAL-1704)
Adjusted donut charts, the legend position was not being used and the styles were not applies properly.
Added subtotals to the legend, in case of web sessions moved the legend right since there's more space (otherwise the donut ends up being even smaller)
> HAL-1704: adjust donut charts 

- app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/DataSourceTemplates.java
(cherry picked from commit 63a689c4154ed44a77a0b80b55fd51a1006712af)
Issue: https://issues.redhat.com/browse/HAL-1723
This was actually fixed in HAL 2.8.26 with https://issues.redhat.com/browse/HAL-1098, in repository https://github.com/hal/core
Old PR https://github.com/hal/core/pull/210, but it seems the fix was not included when migrating HAL code to https://github.com/hal/console in HAL 3 development.
Downstream PR: https://github.com/hal/console/pull/434
> HAL-1723 update url in template for MS SQLServer datasource

- app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/wizard/DataSourceWizard.java
- app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/wizard/DriverStep.java
- core/src/main/java/org/jboss/hal/core/datasource/DataSource.java
Issue: https://issues.redhat.com/browse/HAL-1716
Three main changes done here:
1. Now the `DriverStep` manages `DRIVER_CLASS_NAME` or `DRIVER_XA_DATASOURCE_CLASS_NAME` depending if it is an xa data-source or not.
2. The `DRIVER_XA_DATASOURCE_CLASS_NAME` is now a compulsory attribute (this is a bit strange, because it is compulsory only if the driver has not defined this property, I have added it as compulsory always but we can change this if you prefer).
3. A value change handler has been added to modify that attribute when the driver is changed. The handler first try to add the driver xa data-source class first and, if it's not defined there, the value in the template.
PR for develop branch.
> [HAL-1716] HAL doesn't permit creation of working XA datasource

- app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/DataSourceTemplates.java
https://issues.redhat.com/browse/HAL-1717
HAL-1717 correct Oracle connection URL in template based on https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.3/html-single/configuration_guide/index#datasource_connection_urls
> HAL-1717 correct Oracle connection URL in template

- app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/DataSourceTemplates.java
https://issues.redhat.com/browse/HAL-1721
remove STALE_CONNECTION_CHECKER_CLASS_NAME for DB2XADS
It was previously removed for DB2DS in https://github.com/hal/console/pull/440, but it hasn't been done for DB2XADS
> HAL-1721 remove STALE_CONNECTION_CHECKER_CLASS_NAME for DB2XADS

- app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/DataSourceTemplates.java
- dmr/src/main/java/org/jboss/hal/dmr/ModelDescriptionConstants.java
(cherry picked from commit 5a82f16b8d2282f9efe4703f996100bab4c5ed73)
issue: https://issues.redhat.com/browse/HAL-1715 update Oracle default validation settings
Although I am not sure if this is OK to change default validation settings in a CP release.
JBEAP issue: https://issues.redhat.com/browse/JBEAP-20494
upstream PR: https://github.com/hal/console/pull/426
> HAL-1715 update datasource templates default validation settings

- app/src/main/java/org/jboss/hal/client/runtime/subsystem/ejb/EjbView.java
Upstream Issue: https://issues.redhat.com/browse/HAL-1735
Issue: https://issues.redhat.com/browse/JBEAP-20819
Upstream PR: not required
The EjbView class references the `remove-methods` attribute of the stateful-session-bean resource, which was introduced in Wildfly 20. The JBoss EAP 7.3 is forked from Wildfly 18 so the attribute is not present.
I think the upstream PR is not required as any future version of HAL will not be used with Wildfly 19 or bellow.
> HAL-1735 EjbView references attributes that don't exist in EAP 7.3.x

- dmr/src/main/java/org/jboss/hal/dmr/ResourceAddress.java
- dmr/src/test/java/org/jboss/hal/dmr/ResourceAddressTest.java
Upstream Issue: https://issues.redhat.com/browse/HAL-1742
Upstream PR: https://github.com/hal/console/pull/462
Issue: https://issues.redhat.com/browse/JBEAP-21565
Adding the commit in the related upstream PR and the one that removed the unneeded imports in the class (it was merged later).
> [JBEAP-21565] [HAL-1742] [HAL-1749] Fix address parsing when address contains duplicate parts

- ballroom/src/main/java/org/jboss/hal/ballroom/autocomplete/StringRenderer.java
(cherry picked from commit a801828b25f8394b5facdeee137ea4bc01bb4e0e)
backport upstream fix to 3.2.x branch.
Issue: https://issues.redhat.com/browse/JBEAP-21483
Upstream issue: https://issues.redhat.com/browse/HAL-1745
Upstream PR: https://github.com/hal/console/pull/461
> HAL-1745: Make autosuggestions HTML safe

- ballroom/src/main/java/org/jboss/hal/ballroom/table/DataTable.java
- core/src/main/java/org/jboss/hal/core/modelbrowser/ChildrenPanel.java
Issue: [HAL-1740](https://issues.redhat.com/browse/HAL-1740)
Changed the table buttons in Model Browser tables to properly work with RBAC, the buttons will now be hidden instead of disabled. The disabling wasn't working anyway, since they would get enabled by the default datatable behavior.
> HAL-1740: fix security handling in Model Browser

- ballroom/src/main/java/org/jboss/hal/ballroom/form/TagsItem.java
- core/src/main/java/org/jboss/hal/core/mbui/form/DefaultFormItemProvider.java
- core/src/main/java/org/jboss/hal/core/ui/TuplesListItem.java
- resources/src/main/java/org/jboss/hal/resources/Messages.java
- resources/src/main/resources/org/jboss/hal/resources/Messages.properties
Issue: [HAL-1580](https://issues.redhat.com/browse/HAL-1580)
I've added an item to handle simple lists of objects (i.e. objects that don't have another object or list as a child) to be used by the DefaultFormItemProvider. The list items can be entered either as a comma-separated list of attributes or through an "add resource" dialog.
It's a bit hacky in terms of adding the button to the TagsItem but I don't know if there's a better way to do it without making the appearance from scratch.
This takes care of the client/server interceptors in EJB per the original issue and also several other attributes in Elytron.
> HAL-1580: implement a form item for simple lists of objects

- core/src/main/java/org/jboss/hal/core/ComplexAttributeOperations.java
- core/src/main/java/org/jboss/hal/core/OperationFactory.java
- core/src/main/java/org/jboss/hal/core/elytron/CredentialReference.java
- resources/src/main/java/org/jboss/hal/resources/Messages.java
- resources/src/main/resources/org/jboss/hal/resources/Messages.properties
Issue: https://issues.redhat.com/browse/HAL-1760
Main modifications managing the credential references:
- New `save` method that writes the full object as it is done in the add operation.
- There is a new custom validator that checks the values are OK (if you want any different wording for the messages just let me now).
- The reset link has been removed as makes no sense in a credential-reference (it's always an error).
@hpehl For branch 3.3.x this commit https://github.com/hal/console/commit/85723c303de2f6b911dbd4306fc2356d2515b6ba is also needed. PR: #492
> [HAL-1760] Editing credential reference is not working

- app/src/main/java/org/jboss/hal/client/runtime/subsystem/elytron/StoreElement.java
- app/src/main/java/org/jboss/hal/client/runtime/subsystem/elytron/StoresPresenter.java
- app/src/main/java/org/jboss/hal/client/runtime/subsystem/elytron/StoresView.java
Issue: https://issues.redhat.com/browse/HAL-1762
Changes:
* The buttons have been modified to not enable/disable them manually but using the Scope parameter (there were issues on them).
* The setSecret operation was wrong, it called the remove and besides only the alias form field was passed. It did not work at all.
* The removeAlias called an extra STORE operation that does not exist and triggered an error.
PR for 3.3.x.
PR for develop branch: https://github.com/hal/console/pull/494
> [HAL-1762] Aliases are removed from the credential store when passwords are updated from the admin console

- app/src/main/java/org/jboss/hal/client/configuration/subsystem/messaging/ClusteringPresenter.java
- app/src/main/resources/org/jboss/hal/client/configuration/subsystem/messaging/ClusteringView.mbui.xml
- dmr/src/main/java/org/jboss/hal/dmr/ModelDescriptionConstants.java
- resources/src/main/java/org/jboss/hal/resources/Messages.java
- resources/src/main/resources/org/jboss/hal/resources/Messages.properties
https://issues.redhat.com/browse/HAL-1765
https://issues.redhat.com/browse/JBEAP-23042
Upstream for https://github.com/hal/console/pull/499
This change:
* Makes the jgroups-cluster and socket-bindings fields visible in the Add
form, because setting one of them is required by EAP..
* Adds a form validation that checks that one of the above fields is
configured. The fields are already marked as alternatives in the model
definition.
> HAL-1765 Discovery and broadcast groups can't be created in messaging configuration

- app/src/main/java/org/jboss/hal/client/deployment/ServerGroupDeploymentPreview.java
- app/src/main/java/org/jboss/hal/client/deployment/StandaloneDeploymentPreview.java
https://issues.redhat.com/browse/HAL-1771 
[HAL-1737](https://issues.redhat.com/browse/HAL-1737) adds the ability to view content hash in deployment panel, but I think it should exclude the case of unmanaged deployment. Otherwise, it causes an error when getting content hash for unmanaged deployment.
> [HAL-1771] only display content hash for managed deployment

- ballroom/src/main/java/org/jboss/hal/ballroom/Format.java
Commit 7f5e915b0f6088b9acafeb91f76cbc717f0338eb broke method _humanReadableDuration_: the displayed values could be off by half a minute/hour/day. The comma separator was not used perfectly either.
(I don't think  "2 days, 34 min[utes],(!) sounds weird", but I left that piece of code and comment alone.)
> fixed method humanReadableDuration

- app/Gruntfile.js
- app/package-lock.json
- app/package.json
- app/src/main/java/org/jboss/hal/client/runtime/subsystem/logging/LogFileView.java
- app/src/main/java/org/jboss/hal/client/tools/MacroEditorView.java
- ballroom/src/main/java/org/jboss/hal/ballroom/Clipboard.java
Issue: https://issues.redhat.com/browse/JBEAP-23740
HAL issue: https://issues.redhat.com/browse/HAL-1777
Upstream main branch PR: https://github.com/hal/console/pull/549
I also removed `ZeroClipboard` references in `Gruntfile.js`. But, Do I need to replace them with`clipboard` there?
> HAL-1777: Replace ZeroClipboard with clipboardjs (3.3.x branch)

- app/src/main/java/org/jboss/hal/client/runtime/subsystem/webservice/EndpointColumn.java
- app/src/main/java/org/jboss/hal/client/runtime/subsystem/webservice/EndpointPreview.java
- dmr/src/main/java/org/jboss/hal/dmr/ResourceAddress.java
- dmr/src/test/java/org/jboss/hal/dmr/ResourceAddressTest.java
Issue: https://issues.redhat.com/browse/HAL-1801
Doing the same that was done in other cases. I added a `startsWith` method to not add two times the `/host=*/server=*` in the DC host. Using `WEBSERVICES_RUNTIME_TEMPLATE` to check for statistics because it fails in domain mode (the resolve expressions can only be executed in runtime). A little test for `startsWith` was also added.
This PR is for branch 3.3.x.
PR for main: https://github.com/hal/console/pull/676
> [HAL-1801] No resource definition registered for webservices endpoints on a host slave

- core/src/main/java/org/jboss/hal/core/mvp/Places.java
Issue: https://issues.redhat.com/browse/HAL-1802
After the gwt upgrade to 2.10.0 the location url does not have the # character and the indexOf returns -1. This triggers a StringIndexOutOfBoundsException and a loop in the initialization after login. Tested in chrome and firefox.
> [HAL-1802] HAL console unaviable after gwt upgrade to 2.10.0

- code-parent/pom.xml
Issue: https://issues.redhat.com/browse/HAL-1803
Just excluding the junit5 dependency in elemento-core. The module avoids the execution of the tests (which are using junit4).
> [HAL-1803] Tests are not executed in main

- app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/JdbcDriverPreview.java
- dmr/src/main/java/org/jboss/hal/dmr/ModelDescriptionConstants.java
https://issues.redhat.com/browse/HAL-1816
> [HAL-1816] Hardcoded string "jdbc-compliant" could be replaced by ModelDescriptionConstants

- app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/DataSourceTemplates.java
- app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/wizard/ConnectionStep.java
- app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/wizard/DataSourceWizard.java
- app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/wizard/DriverStep.java
- app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/wizard/PropertiesStep.java
- app/src/main/java/org/jboss/hal/client/configuration/subsystem/datasource/wizard/ReviewStep.java
Issue: [HAL-1850](https://issues.redhat.com/browse/HAL-1850)
There were several instances where the datasource model would have undefined attributes added to it, by working on the model directly instead of a copy, I've eliminated those. Fixed DRIVER_NAME propagation and XA_DATASOURCE_PROPERTIES handling.
Other changes:
* Connection Step: SECURITY_DOMAIN has been deprecated a while ago so I removed it, added AUTHENTICATION_CONTEXT which is the Elytron-based alternative
* Driver Step: removed DRIVER_MODULE_NAME (also from templates), I don't know why this was here in the first place since the value wasn't being used and it's not even a valid dataSource attribute. If it's supposed to be info for the user I can add it back as a readonly field
> HAL-1850: fix and update dataSource wizard

- core/src/main/java/org/jboss/hal/core/subsystem/Subsystems.java
https://issues.redhat.com/browse/HAL-1867
> HAL-1867: Security subsystem should be labeled also as Elytron

- dmr/src/main/java/org/jboss/hal/dmr/dispatch/Dispatcher.java
[HAL-1873] Restore the firing of message event with error message. Fix previous change in https://github.com/hal/console/commit/56cbd8bdf956aa945181801f5d86f13c89c03c7c
Issue: https://issues.redhat.com/browse/HAL-1873
Downstream JBEAP https://issues.redhat.com/browse/JBEAP-25158
> [HAL-1873] Restore the firing of message event with error message

- core/src/main/java/org/jboss/hal/core/modelbrowser/ReadChildren.java
Issue: [HAL-1872](https://issues.redhat.com/browse/HAL-1872)
Changed the ids in the tree panel to follow this pattern
```
ROOT            ROOT
* TYPE         ROOT___TYPE
* NAME       ROOT___TYPE___NAME   (previously just ROOT___NAME)
```
currently if TYPE and NAME are the same word the tree widget stops working.
> HAL-1872: fix id generation in Model Browser

- app/package.json
Issue: https://issues.redhat.com/browse/HAL-1875
`main` branch has upgraded pouchdb to 8.0.1.
> [HAL-1875] Upgrade pouchdb to 8.0.1

- core/src/main/java/org/jboss/hal/core/CrudOperations.java
- core/src/main/java/org/jboss/hal/core/mbui/MbuiViewImpl.java
- dmr/src/main/java/org/jboss/hal/dmr/dispatch/Dispatcher.java
Upstream Issue: https://issues.redhat.com/browse/HAL-1877
Issue: https://issues.redhat.com/browse/JBEAP-25201
Introduces another callback to CrudOperations.save*() methods. The original callback is used when operation succeeds (as was described in Javadocs), and the new callback is triggered on failure. The new error callback is used to call `presenter.reload()`.
MbuiViewImpl.java:
```
protected void saveForm(final String type, final String name, final ResourceAddress address,
final Map<String, Object> changedValues, final Metadata metadata) {
mbuiContext.crud().save(type, name, address, changedValues, metadata, () -> presenter.reload() /* original, on success callback */,
() -> presenter.reload() /* new, on error callback */);
}
```
> HAL-1877 Add error callback parameter to CrudOperations.save()

- core/src/main/java/org/jboss/hal/core/OperationFactory.java
- core/src/main/java/org/jboss/hal/core/mbui/form/FormHelper.java
- core/src/main/java/org/jboss/hal/core/mbui/form/ModelNodeForm.java
Issue: [HAL-1864](https://issues.redhat.com/browse/HAL-1864)
As it turns out there aren't many forms affected by this, at least not in the basic configuration, one of them is the basic form for distributable web.
I changed the alternatives check so that ignores alternatives that are deprecated, this works for e.g. root-logger where `filter-spec` cannot be currently reset because of `filter` (which is also an object so it's not even present in the form).
> HAL-1864: hide reset link if no attributes can be reset

- app/package-lock.json
https://issues.redhat.com/browse/HAL-1880 Upgrade dev dependency semver from 5.7.1 to 5.7.2 
Since 2.9.3 is the latest version of `parcel/transformer-less`, this explicitly upgrades dev dependency semver from 5.7.1 to 5.7.2 
```
hal@ /Users/chaowan/work/git/hal/console/app
├─┬ @parcel/transformer-less@2.9.3
│ └─┬ less@4.1.3
│   └─┬ make-dir@2.1.0
│     └── semver@5.7.1
```
> [HAL-1880] Upgrade semver from 5.7.1 to 5.7.2

- core/src/main/java/org/jboss/hal/core/expression/ExpressionResolver.java
Issue: [HAL-1885](https://issues.redhat.com/browse/HAL-1885)
It's possible to have the same server name among multiple hosts providing the hosts are launched from separate installations (i.e. it doesn't work from a single folder)
> HAL-1885: handle duplicate server names in expression resolution

- app/src/main/java/org/jboss/hal/client/skeleton/HeaderView.java
- resources/src/main/java/org/jboss/hal/resources/Ids.java
Issue: [HAL-1945](https://issues.redhat.com/browse/HAL-1945)
Port of #1013
> HAL-1945: fix notification badge visibility

- app/src/main/resources/org/jboss/hal/client/configuration/subsystem/ejb/EjbView.mbui.xml
The timer service has 4 attributes currently but they are all tied to capability references so we don't have configure custom handlers.
> HAL-1947: fix timer-service attributes handling

- core/src/main/java/org/jboss/hal/core/expression/ExpressionEncryptor.java
- dmr/src/main/java/org/jboss/hal/dmr/ModelDescriptionConstants.java
…rypt Expression code in the ExpressionEncryptor class
> [HAL-1952] Adding String constants in ExpressionEncryptor class.

- meta/src/main/java/org/jboss/hal/meta/AddressTemplate.java
- meta/src/test/java/org/jboss/hal/meta/processing/LookupResultTest.java
- meta/src/test/java/org/jboss/hal/meta/security/ConstraintTest.java
- meta/src/test/java/org/jboss/hal/meta/security/ConstraintsTest.java
Issue: https://issues.redhat.com/browse/HAL-1906
Just for review now. This will likely either need update in PathTemplate JDOC contract or just wont make it.
EDIT: to be precise, it allows delimiter to be part of V.
> [HAL-1906] allow path serparator to be part of KVP

- app/src/main/java/org/jboss/hal/client/deployment/AbstractDeploymentColumn.java
- app/src/main/java/org/jboss/hal/client/deployment/DeploymentTasks.java
Issue: [HAL-1953](https://issues.redhat.com/browse/HAL-1953)
Aside from the deployment not working there was also a problem with `runtime-name` not being treated as optional so I fixed that as well.
> HAL-1953: fix unmanaged deployment for server groups

- app/src/main/java/org/jboss/hal/client/ConsoleModule.java
- app/src/main/java/org/jboss/hal/client/runtime/subsystem/datasource/DataSourceColumn.java
- app/src/main/java/org/jboss/hal/client/runtime/subsystem/datasource/DataSourcePresenter.java
- app/src/main/java/org/jboss/hal/client/runtime/subsystem/datasource/DataSourceXAPresenter.java
- app/src/main/java/org/jboss/hal/client/runtime/subsystem/datasource/DataSourceXAView.java
- meta/src/main/java/org/jboss/hal/meta/token/NameTokens.java
https://issues.redhat.com/browse/JBEAP-26463
Upstream issue: https://issues.redhat.com/browse/HAL-1970
Upstream PR: https://github.com/hal/console/pull/1114
> JBEAP-26463: Split runtime ds presenter/view into xa and non-xa version

- app/src/main/java/org/jboss/hal/client/configuration/subsystem/ejb/AddressTemplates.java
- app/src/main/java/org/jboss/hal/client/configuration/subsystem/ejb/EjbPresenter.java
- app/src/main/java/org/jboss/hal/client/configuration/subsystem/ejb/EjbView.java
- app/src/main/resources/org/jboss/hal/client/configuration/subsystem/ejb/EjbView.mbui.xml
Issue: [HAL-1975](https://issues.redhat.com/browse/HAL-1975)
Added forms/tables for all the child resources under `remoting-profile` (including one "grand-child").
> HAL-1975: add pages for remoting profile children

- ballroom/src/main/java/org/jboss/hal/ballroom/Format.java
(cherry picked from commit 0db4e69eccd6519d6217e4b61a316984ee45ae40)
https://issues.redhat.com/browse/HAL-1976 Status page improperly converts uptime from ms to readable format
This is for 3.3.x branch. 
upstream fixed Upstream PR: https://github.com/hal/console/pull/475
> [HAL-1976] fixed method humanReadableDuration

- app/src/main/java/org/jboss/hal/client/accesscontrol/AccessControlTokens.java
- app/src/main/java/org/jboss/hal/client/deployment/BrowseByColumn.java
- app/src/main/java/org/jboss/hal/client/deployment/ServerGroupDeploymentPreview.java
- app/src/main/java/org/jboss/hal/client/homepage/TourSetup.java
- core/src/main/java/org/jboss/hal/core/finder/FinderPathFactory.java
- resources/src/main/java/org/jboss/hal/resources/Names.java
Issue: [HAL-1984](https://issues.redhat.com/browse/HAL-1984)
Changed the ids to not use localized strings. This completely prevented content-repository from being accessible in locales that aren't using the Latin alphabet. The access control was working but the links were causing visual issues. e.g. items not being correctly highlighted (this was happening even with English locale).
> HAL-1984: fix id generation from proprietary strings

- app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/JdbcRealmElement.java
Issue: [HAL-1987](https://issues.redhat.com/browse/HAL-1987)
I've checked other usages of `.singleton()`, this was the only one without a check.
> fix JDBC realm form ping

- meta/src/main/java/org/jboss/hal/meta/description/ResourceDescription.java
[HAL-1991] Fix AddUnmanagedDialog
Issue: https://issues.redhat.com/browse/HAL-1991
Fix AttributeCollection in `AddUnmanagedDialog`, it should be `attributes()` instead of `requestProperties()`.
Also fix `getAttributes` method in ResourceDescription.java.
The parentValue value type could be LIST for `content` 
Also it's incorrect to assume the `nestedValue` always inherit ACCESS_TYPE value from parent. For example, the `content`'s Access Type is [`read-only`](https://docs.wildfly.org/33/wildscribe/deployment/index.html#attr-content). `content.path` can't be read-only if you want user input in this dialog.
@michpetrov I think you know more about the recent change around this area for #1187, could you review this ?
> [HAL-1991] Fix AddUnmanagedDialog

- app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/OtherSettingsPresenter.java
- app/src/main/java/org/jboss/hal/client/configuration/subsystem/elytron/RealmsPresenter.java
- app/src/main/java/org/jboss/hal/client/configuration/subsystem/undertow/ApplicationSecurityDomainPresenter.java
- app/src/main/java/org/jboss/hal/client/configuration/subsystem/undertow/ApplicationSecurityDomainView.java
- core/src/main/java/org/jboss/hal/core/elytron/CredentialReference.java
One usage of the `copyComplexAttributeAttributes` remains for a list type attribute but I think it might be removed if we made the form use request properties, I haven't tried changing it so I don't break something else.
I will try to improve the credential reference handling, e.g. the validator used in the Elytron presenters doesn't look like it works the same way as the `CredentialReference.CrFormValuesValidation` and requires/alternatives validation doesn't work out of the box on the flattened attributes either, but that's out of the scope for this issue.
> HAL-1990: remove unnecessary copying of complex attributes

- app/src/main/java/org/jboss/hal/client/ConsoleModule.java
- app/src/main/java/org/jboss/hal/client/runtime/subsystem/resourceadapter/AddressTemplates.java
- app/src/main/java/org/jboss/hal/client/runtime/subsystem/resourceadapter/BasePresenter.java
- app/src/main/java/org/jboss/hal/client/runtime/subsystem/resourceadapter/BaseView.java
- app/src/main/java/org/jboss/hal/client/runtime/subsystem/resourceadapter/ChildResourceColumn.java
- app/src/main/java/org/jboss/hal/client/runtime/subsystem/resourceadapter/ChildResourcePresenter.java
- app/src/main/java/org/jboss/hal/client/runtime/subsystem/resourceadapter/ChildResourcePreview.java
- app/src/main/java/org/jboss/hal/client/runtime/subsystem/resourceadapter/ChildResourceView.java
- app/src/main/java/org/jboss/hal/client/runtime/subsystem/resourceadapter/ResourceAdapterColumn.java
- app/src/main/java/org/jboss/hal/client/runtime/subsystem/resourceadapter/ResourceAdapterPresenter.java
- app/src/main/java/org/jboss/hal/client/runtime/subsystem/resourceadapter/ResourceAdapterPreview.java
- app/src/main/java/org/jboss/hal/client/runtime/subsystem/resourceadapter/ResourceAdapterView.java
- app/src/main/java/org/jboss/hal/client/runtime/subsystem/resourceadapter/StatisticsResource.java
- core/src/main/java/org/jboss/hal/core/subsystem/Subsystems.java
- meta/src/main/java/org/jboss/hal/meta/token/NameTokens.java
- resources/src/main/java/org/jboss/hal/resources/Ids.java
- resources/src/main/java/org/jboss/hal/resources/Messages.java
- resources/src/main/java/org/jboss/hal/resources/Names.java
- resources/src/main/java/org/jboss/hal/resources/Previews.java
- resources/src/main/resources/org/jboss/hal/resources/Messages.properties
- resources/src/main/resources/org/jboss/hal/resources/previews/runtime/resource-adapters.html
Issue: [HAL-2006](https://issues.redhat.com/browse/HAL-2006)
There are two types of statistics
* `statistics=pool` on `resource-adapter=*/connection-definitions=*`, this is basically a copy of the pool statistics from datasources and they're always in the model
* `statistics=extended` can be present on `resource-adapter=*`, `resource-adapter=*/connection-definitions=*` and `resource-adapter=*/admin-objects=*`; as far as I can tell there is no expected set of attributes, so we're not showing any charts; I couldn't find any practical examples so I only tested this with some dummy classes
These only work for resource adapters registered in the configuration, WildFly doesn't seem to support getting statistics from deployments atm
> HAL-2006: add runtime view for Resource Adapters statistics

- app/src/main/java/org/jboss/hal/client/runtime/group/ServerGroupColumn.java
- core/src/main/java/org/jboss/hal/core/runtime/group/ServerGroupActions.java
Upstream issue: https://issues.redhat.com/browse/HAL-1955
8.1.x issue: https://issues.redhat.com/browse/JBEAP-29778
The problem was that the `isSuspended()` method was not working correctly for the server groups due to missing runtime data.
The server group column uses: `/host=primary/server-config=...`  (missing runtime data, except for `server-status-config` => `isStopped()` works)
The server column uses: `/host=primary/server=...` (contains runtime data)
The fix was to allow all the actions to be present (depending on the `isStarted()`) within the server group column.
> [HAL-1955, JBEAP-29778] Domain mode has server-group missing Resume operation

- app/src/main/java/org/jboss/hal/client/runtime/group/ServerGroupColumn.java
- core/src/main/java/org/jboss/hal/core/runtime/group/ServerGroupActions.java
Upstream Issue: https://issues.redhat.com/browse/HAL-1955
Upstream PR: https://github.com/hal/console/pull/1363
Issue: https://issues.redhat.com/browse/JBEAP-26190
> The problem was that the `isSuspended()` method was not working correctly for the server groups due to missing runtime data.
> 
> The server group column uses: `/host=primary/server-config=...`  (missing runtime data, except for `server-status-config` => `isStopped()` works)
> The server column uses: `/host=primary/server=...` (contains runtime data)
> 
> The fix was to allow all the actions to be present (depending on the `isStarted()`) within the server group column.
> [JBEAP-26190] Domain mode has server-group missing Resume operation in Web Console

- ballroom/src/main/java/org/jboss/hal/ballroom/chart/Utilization.java
https://issues.redhat.com/browse/HAL-2007
https://issues.redhat.com/browse/JBEAP-28887
upstream PR: https://github.com/hal/console/pull/1297
[Backport [HAL-2007](https://issues.redhat.com/browse/HAL-2007) fix to downstream 3.3 branch]
> [HAL-2007] Fix utilization bar

- app/src/main/java/org/jboss/hal/client/deployment/BrowseContentElement.java
- app/src/main/java/org/jboss/hal/client/deployment/ContentParser.java
- app/src/main/java/org/jboss/hal/client/runtime/configurationchanges/ConfigurationChangeDisplay.java
- app/src/main/java/org/jboss/hal/client/runtime/subsystem/jaxrs/RestResourcePreview.java
- app/src/main/java/org/jboss/hal/client/runtime/subsystem/undertow/DeploymentPreview.java
- ballroom/src/main/java/org/jboss/hal/ballroom/tree/Bridge.java
- ballroom/src/main/java/org/jboss/hal/ballroom/tree/SimpleEventHandler.java
- ballroom/src/main/java/org/jboss/hal/ballroom/tree/Tree.java
- core/src/main/java/org/jboss/hal/core/runtime/server/ServerActions.java
- core/src/main/java/org/jboss/hal/core/runtime/server/ServerUrl.java
- resources/src/main/java/org/jboss/hal/resources/Messages.java
Issue: https://issues.redhat.com/browse/HAL-2020
No upstream required - upstream already fixed.
> HAL-2020 Backport CVE-2025-2901 to 3.3.x

- app/local_modules/parcel-resolver-theme/package-lock.json
- app/package-lock.json
Backporting base-x upgrade to 3.0.11.
Upstream PR: 
https://github.com/hal/console/pull/1370
https://github.com/hal/console/pull/1371
> [HAL-2021] Bump base-x to 3.0.11

- dmr/src/main/java/org/jboss/hal/dmr/BigIntegerModelValue.java
- dmr/src/main/java/org/jboss/hal/dmr/BytesModelValue.java
- dmr/src/main/java/org/jboss/hal/dmr/ModelNode.java
- dmr/src/main/java/org/jboss/hal/dmr/TypeModelValue.java
Issue: [HAL-2022](https://issues.redhat.com/browse/HAL-2022)
For some reason there are discrepancies between the DMR classes in HAL and in jboss-dmr. The major issue was the BIG_INTEGER not writing out the length before the array.
> HAL-2022: sync DMR classes with JBoss
